//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sysLanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmployeeDetailModelValidationMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmployeeDetailModelValidationMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaseFramework.Model.Resource.EmployeeModelValidationMessage.EmployeeDetailDTO.Emp" +
                            "loyeeDetailModelValidationMessage", typeof(EmployeeDetailModelValidationMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Tarihi Alanı Boş Geçilemez.
        /// </summary>
        public static string BirthDateEmployeeDetailRequiredMessage {
            get {
                return ResourceManager.GetString("BirthDateEmployeeDetailRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan Grubu Alanı Boş Geçilemez.
        /// </summary>
        public static string BloodGroupEmployeeDetailRequiredMessage {
            get {
                return ResourceManager.GetString("BloodGroupEmployeeDetailRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğitim Seviyesi Alanı Boş Geçilemez.
        /// </summary>
        public static string EducationLevelEmployeeDetailRequiredMessage {
            get {
                return ResourceManager.GetString("EducationLevelEmployeeDetailRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğitim Durumu Alanı Boş Geçilemez.
        /// </summary>
        public static string EducationStatusEmployeeDetailRequiredMessage {
            get {
                return ResourceManager.GetString("EducationStatusEmployeeDetailRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışan Alanı Boş Geçilemez.
        /// </summary>
        public static string EmployeeEmployeeDetailRequiredMessage {
            get {
                return ResourceManager.GetString("EmployeeEmployeeDetailRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyet Alanı Boş Geçilemez.
        /// </summary>
        public static string GenderEmployeeDetailRequiredMessage {
            get {
                return ResourceManager.GetString("GenderEmployeeDetailRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Tamamlanan Eğitim Kurumu Alanı Boş Geçilemez.
        /// </summary>
        public static string LastCompletedEducationalInstitutionEmployeeDetailRequiredMessage {
            get {
                return ResourceManager.GetString("LastCompletedEducationalInstitutionEmployeeDetailRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medeni Hal Alanı Boş Geçilemez.
        /// </summary>
        public static string MaritalStatusEmployeeDetailRequiredMessage {
            get {
                return ResourceManager.GetString("MaritalStatusEmployeeDetailRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimlik Numarası Alanı Boş Geçilemez.
        /// </summary>
        public static string TCKNEmployeeDetailRequiredMessage {
            get {
                return ResourceManager.GetString("TCKNEmployeeDetailRequiredMessage", resourceCulture);
            }
        }
    }
}
