//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sysLanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoginStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaseFramework.WebUI.Resources.Views.Login.LoginStrings", typeof(LoginStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri.
        /// </summary>
        public static string btn_Back {
            get {
                return ResourceManager.GetString("btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Oluştur.
        /// </summary>
        public static string btn_createaccount {
            get {
                return ResourceManager.GetString("btn_createaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buraya.
        /// </summary>
        public static string btn_here {
            get {
                return ResourceManager.GetString("btn_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string btn_login {
            get {
                return ResourceManager.GetString("btn_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        public static string btn_register {
            get {
                return ResourceManager.GetString("btn_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string btn_Submit {
            get {
                return ResourceManager.GetString("btn_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OopsHR Hoş Geldiniz.
        /// </summary>
        public static string lbl_ContentBody {
            get {
                return ResourceManager.GetString("lbl_ContentBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OopsHR Kullanıcı Girişi.
        /// </summary>
        public static string lbl_ContentTitle {
            get {
                return ResourceManager.GetString("lbl_ContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string plc_Address {
            get {
                return ResourceManager.GetString("plc_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir.
        /// </summary>
        public static string plc_CityTown {
            get {
                return ResourceManager.GetString("plc_CityTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ülke.
        /// </summary>
        public static string plc_Country {
            get {
                return ResourceManager.GetString("plc_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hâla Bir Hesabınız Yok Mu?.
        /// </summary>
        public static string plc_donthaveanaccountyet {
            get {
                return ResourceManager.GetString("plc_donthaveanaccountyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string plc_Email {
            get {
                return ResourceManager.GetString("plc_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrenizi sıfırlamak için e-mail adresinizi giriniz..
        /// </summary>
        public static string plc_emailforresetpassword {
            get {
                return ResourceManager.GetString("plc_emailforresetpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir kullanıcı adı ve şifre giriniz..
        /// </summary>
        public static string plc_enteranyusernameandpassword {
            get {
                return ResourceManager.GetString("plc_enteranyusernameandpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kişisel Bilgilerinizi Giriniz:.
        /// </summary>
        public static string plc_enterpersoneldetails {
            get {
                return ResourceManager.GetString("plc_enterpersoneldetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi Unuttum.
        /// </summary>
        public static string plc_forgetPassword {
            get {
                return ResourceManager.GetString("plc_forgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreni mi Unuttun ?.
        /// </summary>
        public static string plc_forgetpasswordQ {
            get {
                return ResourceManager.GetString("plc_forgetpasswordQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad.
        /// </summary>
        public static string plc_FullName {
            get {
                return ResourceManager.GetString("plc_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merak Etme,.
        /// </summary>
        public static string plc_noworries {
            get {
                return ResourceManager.GetString("plc_noworries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şunlarla Giriş Yapınız.
        /// </summary>
        public static string plc_orloginwith {
            get {
                return ResourceManager.GetString("plc_orloginwith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string plc_password {
            get {
                return ResourceManager.GetString("plc_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni Hatırla.
        /// </summary>
        public static string plc_remember {
            get {
                return ResourceManager.GetString("plc_remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreinizi Tekrar Giriniz.
        /// </summary>
        public static string plc_retypeyourpassword {
            get {
                return ResourceManager.GetString("plc_retypeyourpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt.
        /// </summary>
        public static string plc_SingUp {
            get {
                return ResourceManager.GetString("plc_SingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tıklayarak şifreni sıfırlayabilirsin..
        /// </summary>
        public static string plc_toresetyourpassword {
            get {
                return ResourceManager.GetString("plc_toresetyourpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string plc_username {
            get {
                return ResourceManager.GetString("plc_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı ve Şifre Alanı Boş Geçilemez..
        /// </summary>
        public static string UserNamePasswordValid {
            get {
                return ResourceManager.GetString("UserNamePasswordValid", resourceCulture);
            }
        }
    }
}
