//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sysLanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CompanyDepartmentsControllerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompanyDepartmentsControllerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaseFramework.WebAPI.Resources.Controller.CompanyDepartmentsController.CompanyDep" +
                            "artmentsControllerStrings", typeof(CompanyDepartmentsControllerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departman Eklenirken Sorun Oluştu.
        /// </summary>
        public static string add_department {
            get {
                return ResourceManager.GetString("add_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departman Silindi.
        /// </summary>
        public static string delete_department {
            get {
                return ResourceManager.GetString("delete_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departman Silinirken Sorun Oluştu.
        /// </summary>
        public static string delete_departmentError {
            get {
                return ResourceManager.GetString("delete_departmentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depertman Bulunamadı.
        /// </summary>
        public static string id_department {
            get {
                return ResourceManager.GetString("id_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departman Güncellenirken Sorun Oluştu.
        /// </summary>
        public static string update_department {
            get {
                return ResourceManager.GetString("update_department", resourceCulture);
            }
        }
    }
}
