namespace BaseFramework.Dal.Migrations
{
    using BaseFramework.Entity;
    using BaseFramework.Entity.ProjectBaseEntity;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<BaseFramework.Dal.BaseFrameworkEntities>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
        }

        protected override void Seed(BaseFramework.Dal.BaseFrameworkEntities context)
        {
            IList<Country> countries = new List<Country>() {
                 new Country(){Id=1, CountryName = "Türkiye", Code = "+90", LangCode = "Tr-tr",},
                 new Country(){Id=2,CountryName = "England",Code = "+44",LangCode = "En-en",}
            };

            context.Countries.AddRange(countries);

            IList<City> cities = new List<City>()
            {
                new City()  { Id =1,CountryId = 1,Name =  "ADANA",Code =  "322" }   ,
                 new City()  { Id =2,CountryId = 1,Name =  "ADIYAMAN" ,Code =  "416" }   ,
                 new City()  { Id =3,CountryId = 1,Name =  "AFYON",Code =  "272" }   ,
                 new City()  { Id =4,CountryId = 1,Name =  "AĞRI" ,Code =  "472" }   ,
                 new City()  { Id =5,CountryId = 1,Name =  "AKSARAY" ,   Code =  "382" }   ,
                 new City()  { Id =6,CountryId = 1,Name =  "AMASYA",Code =  "358" }   ,
                 new City()  { Id =7,CountryId = 1,Name =  "ANKARA",Code =  "312" }   ,
                 new City()  { Id =8,CountryId = 1,Name =  "ANTALYA" ,   Code =  "242" }   ,
                 new City()  { Id =9,CountryId = 1,Name =  "ARDAHAN" ,   Code =  "478" }   ,
                 new City()  { Id =10,CountryId = 1,Name =  "ARTVİN",Code =  "466" }   ,
                 new City()  { Id =11,CountryId = 1,Name =  "AYDIN",Code =  "256" }   ,
                 new City()  { Id =12,CountryId = 1,Name =  "BALIKESİR",Code =  "266" }   ,
                 new City()  { Id =13,CountryId = 1,Name =  "BARTIN",Code =  "378" }   ,
                 new City()  { Id =14,CountryId = 1,Name =  "BATMAN",Code =  "488" }   ,
                 new City()  { Id =15,CountryId = 1,Name =  "BAYBURT" ,   Code =  "458" }   ,
                 new City()  { Id =16,CountryId = 1,Name =  "BİLECİK" ,   Code =  "228" }   ,
                 new City()  { Id =17,CountryId = 1,Name =  "BİNGÖL",Code =  "426" }   ,
                 new City()  { Id =18,CountryId = 1,Name =  "BİTLİS",Code =  "434" }   ,
                 new City()  { Id =19,CountryId = 1,Name =  "BOLU" ,Code =  "374" }   ,
                 new City()  { Id =20,CountryId = 1,Name =  "BURDUR",Code =  "248" }   ,
                 new City()  { Id =21,CountryId = 1,Name =  "BURSA",Code =  "224" }   ,
                 new City()  { Id =22,CountryId = 1,Name =  "ÇANAKKALE",Code =  "286" }   ,
                 new City()  { Id =23,CountryId = 1,Name =  "ÇANKIRI" ,   Code =  "376" }   ,
                 new City()  { Id =24,CountryId = 1,Name =  "ÇORUM",Code =  "364" }   ,
                 new City()  { Id =25,CountryId = 1,Name =  "DENİZLİ" ,   Code =  "258" }   ,
                 new City()  { Id =26,CountryId = 1,Name =  "DİYARBAKIR",Code =  "412" }   ,
                 new City()  { Id =27,CountryId = 1,Name =  "DÜZCE",Code =  "380" }   ,
                 new City()  { Id =28,CountryId = 1,Name =  "EDİRNE",Code =  "284" }   ,
                 new City()  { Id =29,CountryId = 1,Name =  "ELAZIĞ",Code =  "424" }   ,
                 new City()  { Id =30,CountryId = 1,Name =  "ERZİNCAN" ,Code =  "446" }   ,
                 new City()  { Id =31,CountryId = 1,Name =  "ERZURUM" ,   Code =  "442" }   ,
                 new City()  { Id =32,CountryId = 1,Name =  "ESKİŞEHİR",Code =  "222" }   ,
                 new City()  { Id =33,CountryId = 1,Name =  "GAZİANTEP",Code =  "342" }   ,
                 new City()  { Id =34,CountryId = 1,Name =  "GİRESUN" ,   Code =  "454" }   ,
                 new City()  { Id =35,CountryId = 1,Name =  "GÜMÜŞHANE",Code =  "456" }   ,
                 new City()  { Id =36,CountryId = 1,Name =  "HAKKARİ" ,   Code =  "438" }   ,
                 new City()  { Id =37,CountryId = 1,Name =  "HATAY",Code =  "326" }   ,
                 new City()  { Id =38,CountryId = 1,Name =  "IĞDIR",Code =  "476" }   ,
                 new City()  { Id =39,CountryId = 1,Name =  "ISPARTA" ,   Code =  "246" }   ,
                 new City()  { Id =40,CountryId = 1,Name =  "İÇEL (MERSİN)",Code =  "324" }   ,
                 new City()  { Id =41,CountryId = 1,Name =  "İSTANBUL (AVRUPA YAKASI)" ,Code =  "212" }   ,
                 new City()  { Id =42,CountryId = 1,Name =  "İSTANBUL (ANADOLU YAKASI)",Code =  "216" }   ,
                 new City()  { Id =43,CountryId = 1,Name =  "İZMİR",Code =  "232" }   ,
                 new City()  { Id =44,CountryId = 1,Name =  "KARABÜK" ,   Code =  "370" }   ,
                 new City()  { Id =45,CountryId = 1,Name =  "KARAMAN" ,   Code =  "338" }   ,
                 new City()  { Id =46,CountryId = 1,Name =  "KARS" ,Code =  "474" }   ,
                 new City()  { Id =47,CountryId = 1,Name =  "KASTAMONU",Code =  "366" }   ,
                 new City()  { Id =48,CountryId = 1,Name =  "KAYSERİ" ,   Code =  "352" }   ,
                 new City()  { Id =49,CountryId = 1,Name =  "KIRIKKALE",Code =  "318" }   ,
                 new City()  { Id =50,CountryId = 1,Name =  "KIRKLARELİ",Code =  "288" }   ,
                 new City()  { Id =51,CountryId = 1,Name =  "KIRŞEHİR" ,Code =  "386" }   ,
                 new City()  { Id =52,CountryId = 1,Name =  "KİLİS",Code =  "348" }   ,
                 new City()  { Id =53,CountryId = 1,Name =  "K.MARAŞ" ,   Code =  "344" }   ,
                 new City()  { Id =54,CountryId = 1,Name =  "KOCAELİ" ,   Code =  "262" }   ,
                 new City()  { Id =55,CountryId = 1,Name =  "KONYA",Code =  "332" }   ,
                 new City()  { Id =56,CountryId = 1,Name =  "KÜTAHYA" ,   Code =  "274" }   ,
                 new City()  { Id =57,CountryId = 1,Name =  "MALATYA" ,   Code =  "422" }   ,
                 new City()  { Id =58,CountryId = 1,Name =  "MANİSA",Code =  "236" }   ,
                 new City()  { Id =59,CountryId = 1,Name =  "MARDİN",Code =  "482" }   ,
                 new City()  { Id =60,CountryId = 1,Name =  "MUĞLA",Code =  "252" }   ,
                 new City()  { Id =61,CountryId = 1,Name =  "MUŞ" ,   Code =  "436" }   ,
                 new City()  { Id =62,CountryId = 1,Name =  "NEVŞEHİR" ,Code =  "384" }   ,
                 new City()  { Id =63,CountryId = 1,Name =  "NİĞDE",Code =  "388" }   ,
                 new City()  { Id =64,CountryId = 1,Name =  "ORDU" ,Code =  "452" }   ,
                 new City()  { Id =65,CountryId = 1,Name =  "OSMANİYE" ,Code =  "328" }   ,
                 new City()  { Id =66,CountryId = 1,Name =  "RİZE" ,Code =  "464" }   ,
                 new City()  { Id =67,CountryId = 1,Name =  "SAKARYA" ,   Code =  "264" }   ,
                 new City()  { Id =68,CountryId = 1,Name =  "SAMSUN",Code =  "362" }   ,
                 new City()  { Id =69,CountryId = 1,Name =  "SİİRT",Code =  "484" }   ,
                 new City()  { Id =70,CountryId = 1,Name =  "SİNOP",Code =  "368" }   ,
                 new City()  { Id =71,CountryId = 1,Name =  "SİVAS",Code =  "346" }   ,
                 new City()  { Id =72,CountryId = 1,Name =  "ŞANLIURFA",Code =  "414" }   ,
                 new City()  { Id =73,CountryId = 1,Name =  "ŞIRNAK",Code =  "486" }   ,
                 new City()  { Id =74,CountryId = 1,Name =  "TEKİRDAĞ" ,Code =  "282" }   ,
                 new City()  { Id =75,CountryId = 1,Name =  "TOKAT",Code =  "356" }   ,
                 new City()  { Id =76,CountryId = 1,Name =  "TRABZON" ,   Code =  "462" }   ,
                 new City()  { Id =77,CountryId = 1,Name =  "TUNCELİ" ,   Code =  "428" }   ,
                 new City()  { Id =78,CountryId = 1,Name =  "UŞAK" ,Code =  "276" }   ,
                 new City()  { Id =79,CountryId = 1,Name =  "VAN" ,   Code =  "432" }   ,
                 new City()  { Id =80,CountryId = 1,Name =  "YALOVA",Code =  "226" }   ,
                 new City()  { Id =81,CountryId = 1,Name =  "YOZGAT",Code =  "354" }   ,
                 new City()  { Id =82,CountryId = 1,Name =  "ZONGULDAK",Code =  "372" }
            };

            context.Cities.AddRange(cities);

            IList<District> districts = new List<District>()
            {
                new District()  {Id=1,CityId =1,Name ="Aladağ",Code = "322"},
                new District()  {Id=2,CityId =1,Name ="Ceyhan",Code = "322"},
                new District()  {Id=3,CityId =1,Name ="Çukurova	"   ,Code = "322"},
                new District()  {Id=4,CityId =1,Name ="Feke	"   ,Code = "322"},
                new District()  {Id=5,CityId =1,Name ="İmamoğlu	"   ,Code = "322"},
                new District()  {Id=6,CityId =1,Name ="Karaisalı	"  ,Code = "322"},
                new District()  {Id=7,CityId =1,Name ="Karataş	",Code = "322"},
                new District()  {Id=8,CityId =1,Name ="Kozan	"  ,Code = "322"},
                new District()  {Id=9,CityId =1,Name ="Pozantı	",Code = "322"},
                new District()  {Id=10,CityId =1,Name ="Saimbeyli	"  ,Code = "322"},
                new District()  {Id=11,CityId =1,Name ="Sarıçam	",Code = "322"},
                new District()  {Id=12,CityId =1,Name ="Seyhan",Code = "322"},
                new District()  {Id=13,CityId =1,Name ="Tufanbeyli",Code = "322"},
                new District()  {Id=14,CityId =1,Name ="Yumurtalık",Code = "322"},
                new District()  {Id=15,CityId =1,Name ="Yüreğir	",Code = "322"},
                new District()  {Id=16,CityId =2,Name ="Besni	"   ,Code =  "416" }  ,
                new District()  {Id=17,CityId =2,Name ="Çelikhan	"    ,Code =  "416" }  ,
                new District()  {Id=18,CityId =2,Name ="Gerger	"  ,Code =  "416" }  ,
                new District()  {Id=19,CityId =2,Name ="Gölbaşı",Code =  "416" }  ,
                new District()  {Id=20,CityId =2,Name ="Kahta	"   ,Code =  "416" }  ,
                new District()  {Id=21,CityId =2,Name ="Merkez	"  ,Code =  "416" }  ,
                new District()  {Id=22,CityId =2,Name ="Samsat	"  ,Code =  "416" }  ,
                new District()  {Id=23,CityId =2,Name ="Sincik	"  ,Code =  "416" }  ,
                new District()  {Id=24,CityId =2,Name ="Tut",Code =  "416" }  ,
                new District()  {Id=25,CityId =3,Name ="Başmakçı	"     ,Code =  "272" }  ,
                new District()  {Id=26,CityId =3,Name ="Bayat	"    ,Code =  "272" }  ,
                new District()  {Id=27,CityId =3,Name ="Bolvadin	"     ,Code =  "272" }  ,
                new District()  {Id=28,CityId =3,Name ="Çay	"  ,Code =  "272" }  ,
                new District()  {Id=29,CityId =3,Name ="Çobanlar	"     ,Code =  "272" }  ,
                new District()  {Id=30,CityId =3,Name ="Dazkırı	"  ,Code =  "272" }  ,
                new District()  {Id=31,CityId =3,Name ="Dinar	"    ,Code =  "272" }  ,
                new District()  {Id=32,CityId =3,Name ="Emirdağ	"  ,Code =  "272" }  ,
                new District()  {Id=33,CityId =3,Name ="Evciler	"  ,Code =  "272" }  ,
                new District()  {Id=34,CityId =3,Name ="Hocalar	"  ,Code =  "272" }  ,
                new District()  {Id=35,CityId =3,Name ="İhsaniye	"     ,Code =  "272" }  ,
                new District()  {Id=36,CityId =3,Name ="İscehisar	"    ,Code =  "272" }  ,
                new District()  {Id=37,CityId =3,Name ="Kızılören	"    ,Code =  "272" }  ,
                new District()  {Id=38,CityId =3,Name ="Merkez	"   ,Code =  "272" }  ,
                new District()  {Id=39,CityId =3,Name ="Sandıklı	"     ,Code =  "272" }  ,
                new District()  {Id=40,CityId =3,Name ="Sinanpaşa	"    ,Code =  "272" }  ,
                new District()  {Id=41,CityId =3,Name ="Şuhut	"    ,Code =  "272" }  ,
                new District()  {Id=42,CityId =3,Name ="Sultandağı	"   ,Code =  "272" }  ,
                new District()  {Id=43,CityId =4,Name ="Diyadin	" ,   Code =  "472" }  ,
                new District()  {Id=44,CityId =4,Name ="Doğubayazıt	" ,   Code =  "472" }  ,
                new District()  {Id=45,CityId =4,Name ="Eleşkirt",Code =  "472" }  ,
                new District()  {Id=46,CityId =4,Name ="Hamur	",Code =  "472" }  ,
                new District()  {Id=47,CityId =4,Name ="Merkez	",Code =  "472" }  ,
                new District()  {Id=48,CityId =4,Name ="Patnos	",Code =  "472" }  ,
                new District()  {Id=49,CityId =4,Name ="Taşlıçay",Code =  "472" }  ,
                new District()  {Id=50,CityId =4,Name ="Tutak	",Code =  "472" }  ,
                new District()  {Id=51,CityId =5,Name ="Ağaçören",Code =  "382" }  ,
                new District()  {Id=52,CityId =5,Name ="Eskil	",Code =  "382" }  ,
                new District()  {Id=53,CityId =5,Name ="Gülağaç	" ,   Code =  "382" }  ,
                new District()  {Id=54,CityId =5,Name ="Güzelyurt	",Code =  "382" }  ,
                new District()  {Id=55,CityId =5,Name ="Merkez	",Code =  "382" }  ,
                new District()  {Id=56,CityId =5,Name ="Ortaköy	" ,   Code =  "382" }  ,
                new District()  {Id=57,CityId =5,Name ="Sarıyahşi	",Code =  "382" }  ,
                new District()  {Id=58,CityId =5,Name ="Sultanhanı	",Code =  "382" }  ,
                new District()  {Id=59,CityId =6,Name ="Göynücek",Code =  "358" }  ,
                new District()  {Id=60,CityId =6,Name ="Gümüşhacıköy",Code =  "358" }  ,
                new District()  {Id=61,CityId =6,Name ="Hamamözü",Code =  "358" }  ,
                new District()  {Id=62,CityId =6,Name ="Merkez	",Code =  "358" }  ,
                new District()  {Id=63,CityId =6,Name ="Merzifon",Code =  "358" }  ,
                new District()  {Id=64,CityId =6,Name ="Suluova	" ,   Code =  "358" }  ,
                new District()  {Id=65,CityId =6,Name ="Taşova	",Code =  "358" }  ,
                new District()  {Id=66,CityId =7,Name ="Akyurt	",Code =  "312" }  ,
                new District()  {Id=67,CityId =7,Name ="Altındağ",Code =  "312" }  ,
                new District()  {Id=68,CityId =7,Name ="Ayaş",Code =  "312" }  ,
                new District()  {Id=69,CityId =7,Name ="Bala",Code =  "312" }  ,
                new District()  {Id=70,CityId =7,Name ="Beypazarı	",Code =  "312" }  ,
                new District()  {Id=71,CityId =7,Name ="Çamlıdere	",Code =  "312" }  ,
                new District()  {Id=72,CityId =7,Name ="Çankaya	" ,   Code =  "312" }  ,
                new District()  {Id=73,CityId =7,Name ="Çubuk	",Code =  "312" }  ,
                new District()  {Id=74,CityId =7,Name ="Elmadağ	" ,   Code =  "312" }  ,
                new District()  {Id=75,CityId =7,Name ="Etimesgut	",Code =  "312" }  ,
                new District()  {Id=76,CityId =7,Name ="Evren	",Code =  "312" }  ,
                new District()  {Id=77,CityId =7,Name ="Gölbaşı	" ,   Code =  "312" }  ,
                new District()  {Id=78,CityId =7,Name ="Güdül	",Code =  "312" }  ,
                new District()  {Id=79,CityId =7,Name ="Haymana	" ,   Code =  "312" }  ,
                new District()  {Id=80,CityId =7,Name ="Kahramankazan	",Code =  "312" }  ,
                new District()  {Id=81,CityId =7,Name ="Kalecik	" ,   Code =  "312" }  ,
                new District()  {Id=82,CityId =7,Name ="Keçiören",Code =  "312" }  ,
                new District()  {Id=83,CityId =7,Name ="Kızılcahamam",Code =  "312" }  ,
                new District()  {Id=84,CityId =7,Name ="Mamak	",Code =  "312" }  ,
                new District()  {Id=85,CityId =7,Name ="Nallıhan",Code =  "312" }  ,
                new District()  {Id=86,CityId =7,Name ="Polatlı	" ,   Code =  "312" }  ,
                new District()  {Id=87,CityId =7,Name ="Pursaklar	",Code =  "312" }  ,
                new District()  {Id=88,CityId =7,Name ="Şereflikoçhisar	" ,   Code =  "312" }  ,
                new District()  {Id=89,CityId =7,Name ="Sincan	",Code =  "312" }  ,
                new District()  {Id=90,CityId =7,Name ="Yenimahalle	" ,   Code =  "312" }  ,
                new District()  {Id=91,CityId =8,Name ="Akseki	",Code =  "242" }  ,
                new District()  {Id=92,CityId =8,Name ="Aksu",Code =  "242" }  ,
                new District()  {Id=93,CityId =8,Name ="Alanya	",Code =  "242" }  ,
                new District()  {Id=94,CityId =8,Name ="Demre	",Code =  "242" }  ,
                new District()  {Id=95,CityId =8,Name ="Döşemealtı	",Code =  "242" }  ,
                new District()  {Id=96,CityId =8,Name ="Elmalı	",Code =  "242" }  ,
                new District()  {Id=97,CityId =8,Name ="Finike	",Code =  "242" }  ,
                new District()  {Id=98,CityId =8,Name ="Gazipaşa",Code =  "242" }  ,
                new District()  {Id=99,CityId =8,Name ="Gündoğmuş	",Code =  "242" }  ,
                new District()  {Id=100 ,   CityId =8,Name ="İbradı	",Code =  "242" }  ,
                new District()  {Id=101 ,   CityId =8,Name ="Kaş	" ,   Code =  "242" }  ,
                new District()  {Id=102 ,   CityId =8,Name ="Kemer	",Code =  "242" }  ,
                new District()  {Id=103 ,   CityId =8,Name ="Kepez	",Code =  "242" }  ,
                new District()  {Id=104 ,   CityId =8,Name ="Konyaaltı	",Code =  "242" }  ,
                new District()  {Id=105 ,   CityId =8,Name ="Korkuteli	",Code =  "242" }  ,
                new District()  {Id=106 ,   CityId =8,Name ="Kumluca	" ,   Code =  "242" }  ,
                new District()  {Id=107 ,   CityId =8,Name ="Manavgat",Code =  "242" }  ,
                new District()  {Id=108 ,   CityId =8,Name ="Muratpaşa	",Code =  "242" }  ,
                new District()  {Id=109 ,   CityId =8,Name ="Serik	",Code =  "242" }  ,
                new District()  {Id=110 ,   CityId =9,Name ="Çıldır	",Code =  "478" }  ,
                new District()  {Id=111 ,   CityId =9,Name ="Damal	",Code =  "478" }  ,
                new District()  {Id=112 ,   CityId =9,Name ="Göle",Code =  "478" }  ,
                new District()  {Id=113 ,   CityId =9,Name ="Hanak	",Code =  "478" }  ,
                new District()  {Id=114 ,   CityId =9,Name ="Merkez	",Code =  "478" }  ,
                new District()  {Id=115 ,   CityId =9,Name ="Posof	",Code =  "478" }  ,
                new District()  {Id=116 ,   CityId =10,Name ="Ardanuç	" ,   Code =  "466" }  ,
                new District()  {Id=117 ,   CityId =10,Name ="Arhavi	",Code =  "466" }  ,
                new District()  {Id=118 ,   CityId =10,Name ="Borçka	",Code =  "466" }  ,
                new District()  {Id=119 ,   CityId =10,Name ="Hopa",Code =  "466" }  ,
                new District()  {Id=120 ,   CityId =10,Name ="Kemalpaşa	",Code =  "466" }  ,
                new District()  {Id=121 ,   CityId =10,Name ="Merkez	",Code =  "466" }  ,
                new District()  {Id=122 ,   CityId =10,Name ="Murgul	",Code =  "466" }  ,
                new District()  {Id=123 ,   CityId =10,Name ="Şavşat	",Code =  "466" }  ,
                new District()  {Id=124 ,   CityId =10,Name ="Yusufeli",Code =  "466" }  ,
                new District()  {Id=125 ,   CityId =11,Name ="Bozdoğan",Code =  "256" }  ,
                new District()  {Id=126 ,   CityId =11,Name ="Buharkent	",Code =  "256" }  ,
                new District()  {Id=127 ,   CityId =11,Name ="Çine",Code =  "256" }  ,
                new District()  {Id=128 ,   CityId =11,Name ="Didim	",Code =  "256" }  ,
                new District()  {Id=129 ,   CityId =11,Name ="Efeler	",Code =  "256" }  ,
                new District()  {Id=130 ,   CityId =11,Name ="Germencik	",Code =  "256" }  ,
                new District()  {Id=131 ,   CityId =11,Name ="İncirliova	",Code =  "256" }  ,
                new District()  {Id=132 ,   CityId =11,Name ="Karacasu",Code =  "256" }  ,
                new District()  {Id=133 ,   CityId =11,Name ="Karpuzlu",Code =  "256" }  ,
                new District()  {Id=134 ,   CityId =11,Name ="Koçarlı	" ,   Code =  "256" }  ,
                new District()  {Id=135 ,   CityId =11,Name ="Köşk",Code =  "256" }  ,
                new District()  {Id=136 ,   CityId =11,Name ="Kuşadası",Code =  "256" }  ,
                new District()  {Id=137 ,   CityId =11,Name ="Kuyucak	" ,   Code =  "256" }  ,
                new District()  {Id=138 ,   CityId =11,Name ="Nazilli	" ,   Code =  "256" }  ,
                new District()  {Id=139 ,   CityId =11,Name ="Söke",Code =  "256" }  ,
                new District()  {Id=140 ,   CityId =11,Name ="Sultanhisar	" ,   Code =  "256" }  ,
                new District()  {Id=141 ,   CityId =11,Name ="Yenipazar	",Code =  "256" }  ,
                new District()  {Id=142 ,   CityId =12,Name ="Altıeylül	",Code =  "266" }  ,
                new District()  {Id=143 ,   CityId =12,Name ="Ayvalık	" ,   Code =  "266" }  ,
                new District()  {Id=144 ,   CityId =12,Name ="Balya	",Code =  "266" }  ,
                new District()  {Id=145 ,   CityId =12,Name ="Bandırma",Code =  "266" }  ,
                new District()  {Id=146 ,   CityId =12,Name ="Bigadiç	" ,   Code =  "266" }  ,
                new District()  {Id=147 ,   CityId =12,Name ="Burhaniye	",Code =  "266" }  ,
                new District()  {Id=148 ,   CityId =12,Name ="Dursunbey	",Code =  "266" }  ,
                new District()  {Id=149 ,   CityId =12,Name ="Edremit	" ,   Code =  "266" }  ,
                new District()  {Id=150 ,   CityId =12,Name ="Erdek	",Code =  "266" }  ,
                new District()  {Id=151 ,   CityId =12,Name ="Gömeç	",Code =  "266" }  ,
                new District()  {Id=152 ,   CityId =12,Name ="Gönen	",Code =  "266" }  ,
                new District()  {Id=153 ,   CityId =12,Name ="Havran	",Code =  "266" }  ,
                new District()  {Id=154 ,   CityId =12,Name ="İvrindi	" ,   Code =  "266" }  ,
                new District()  {Id=155 ,   CityId =12,Name ="Karesi	",Code =  "266" }  ,
                new District()  {Id=156 ,   CityId =12,Name ="Kepsut	",Code =  "266" }  ,
                new District()  {Id=157 ,   CityId =12,Name ="Manyas	",Code =  "266" }  ,
                new District()  {Id=158 ,   CityId =12,Name ="Marmara	" ,   Code =  "266" }  ,
                new District()  {Id=159 ,   CityId =12,Name ="Savaştepe	",Code =  "266" }  ,
                new District()  {Id=160 ,   CityId =12,Name ="Sındırgı",Code =  "266" }  ,
                new District()  {Id=161 ,   CityId =12,Name ="Susurluk",Code =  "266" }  ,
                new District()  {Id=162 ,   CityId =13,Name ="Amasra	",Code =  "378" }  ,
                new District()  {Id=163 ,   CityId =13,Name ="Kurucaşile	",Code =  "378" }  ,
                new District()  {Id=164 ,   CityId =13,Name ="Merkez	",Code =  "378" }  ,
                new District()  {Id=165 ,   CityId =13,Name ="Ulus",Code =  "378" }  ,
                new District()  {Id=166 ,   CityId =14,Name ="Beşiri	",Code =  "488" }  ,
                new District()  {Id=167 ,   CityId =14,Name ="Gercüş	",Code =  "488" }  ,
                new District()  {Id=168 ,   CityId =14,Name ="Hasankeyf	",Code =  "488" }  ,
                new District()  {Id=169 ,   CityId =14,Name ="Kozluk	",Code =  "488" }  ,
                new District()  {Id=170 ,   CityId =14,Name ="Merkez	",Code =  "488" }  ,
                new District()  {Id=171 ,   CityId =14,Name ="Sason	",Code =  "488" }  ,
                new District()  {Id=172 ,   CityId =15,Name ="Aydıntepe	",Code =  "458" }  ,
                new District()  {Id=173 ,   CityId =15,Name ="Demirözü",Code =  "458" }  ,
                new District()  {Id=174 ,   CityId =15,Name ="Merkez	",Code =  "458" }  ,
                new District()  {Id=175 ,   CityId =16,Name ="Bozüyük	" ,   Code =  "228" }  ,
                new District()  {Id=176 ,   CityId =16,Name ="Gölpazarı	",Code =  "228" }  ,
                new District()  {Id=177 ,   CityId =16,Name ="İnhisar	" ,   Code =  "228" }  ,
                new District()  {Id=178 ,   CityId =16,Name ="Merkez	",Code =  "228" }  ,
                new District()  {Id=179 ,   CityId =16,Name ="Osmaneli",Code =  "228" }  ,
                new District()  {Id=180 ,   CityId =16,Name ="Pazaryeri	",Code =  "228" }  ,
                new District()  {Id=181 ,   CityId =16,Name ="Söğüt	",Code =  "228" }  ,
                new District()  {Id=182 ,   CityId =16,Name ="Yenipazar	",Code =  "228" }  ,
                new District()  {Id=183 ,   CityId =17,Name ="Adaklı	",Code =  "426" }  ,
                new District()  {Id=184 ,   CityId =17,Name ="Genç",Code =  "426" }  ,
                new District()  {Id=185 ,   CityId =17,Name ="Karlıova",Code =  "426" }  ,
                new District()  {Id=186 ,   CityId =17,Name ="Kiğı",Code =  "426" }  ,
                new District()  {Id=187 ,   CityId =17,Name ="Merkez	",Code =  "426" }  ,
                new District()  {Id=188 ,   CityId =17,Name ="Solhan	",Code =  "426" }  ,
                new District()  {Id=189 ,   CityId =17,Name ="Yayladere	",Code =  "426" }  ,
                new District()  {Id=190 ,   CityId =17,Name ="Yedisu	",Code =  "426" }  ,
                new District()  {Id=191 ,   CityId =18,Name ="Adilcevaz	",Code =  "434" }  ,
                new District()  {Id=192 ,   CityId =18,Name ="Ahlat	",Code =  "434" }  ,
                new District()  {Id=193 ,   CityId =18,Name ="Güroymak",Code =  "434" }  ,
                new District()  {Id=194 ,   CityId =18,Name ="Hizan	",Code =  "434" }  ,
                new District()  {Id=195 ,   CityId =18,Name ="Merkez	",Code =  "434" }  ,
                new District()  {Id=196 ,   CityId =18,Name ="Mutki	",Code =  "434" }  ,
                new District()  {Id=197 ,   CityId =18,Name ="Tatvan	",Code =  "434" }  ,
                new District()  {Id=198 ,   CityId =19,Name ="Dörtdivan	",Code =  "374" }  ,
                new District()  {Id=199 ,   CityId =19,Name ="Gerede	",Code =  "374" }  ,
                new District()  {Id=200 ,   CityId =19,Name ="Göynük	",Code =  "374" }  ,
                new District()  {Id=201 ,   CityId =19,Name ="Kıbrıscık	",Code =  "374" }  ,
                new District()  {Id=202 ,   CityId =19,Name ="Mengen	",Code =  "374" }  ,
                new District()  {Id=203 ,   CityId =19,Name ="Merkez	",Code =  "374" }  ,
                new District()  {Id=204 ,   CityId =19,Name ="Mudurnu	" ,   Code =  "374" }  ,
                new District()  {Id=205 ,   CityId =19,Name ="Seben	",Code =  "374" }  ,
                new District()  {Id=206 ,   CityId =19,Name ="Yeniçağa",Code =  "374" }  ,
                new District()  {Id=207 ,   CityId =20,Name ="Ağlasun	" ,   Code =  "248" }  ,
                new District()  {Id=208 ,   CityId =20,Name ="Altınyayla	",Code =  "248" }  ,
                new District()  {Id=209 ,   CityId =20,Name ="Bucak	",Code =  "248" }  ,
                new District()  {Id=210 ,   CityId =20,Name ="Çavdır	",Code =  "248" }  ,
                new District()  {Id=211 ,   CityId =20,Name ="Çeltikçi",Code =  "248" }  ,
                new District()  {Id=212 ,   CityId =20,Name ="Gölhisar",Code =  "248" }  ,
                new District()  {Id=213 ,   CityId =20,Name ="Karamanlı	",Code =  "248" }  ,
                new District()  {Id=214 ,   CityId =20,Name ="Kemer	",Code =  "248" }  ,
                new District()  {Id=215 ,   CityId =20,Name ="Merkez	",Code =  "248" }  ,
                new District()  {Id=216 ,   CityId =20,Name ="Tefenni	" ,   Code =  "248" }  ,
                new District()  {Id=217 ,   CityId =20,Name ="Yeşilova",Code =  "248" }  ,
                new District()  {Id=218 ,   CityId =21,Name ="Büyükorhan	",Code =  "224" }  ,
                new District()  {Id=219 ,   CityId =21,Name ="Gemlik	",Code =  "224" }  ,
                new District()  {Id=220 ,   CityId =21,Name ="Gürsu	",Code =  "224" }  ,
                new District()  {Id=221 ,   CityId =21,Name ="Harmancık	",Code =  "224" }  ,
                new District()  {Id=222 ,   CityId =21,Name ="İnegöl	",Code =  "224" }  ,
                new District()  {Id=223 ,   CityId =21,Name ="İznik	",Code =  "224" }  ,
                new District()  {Id=224 ,   CityId =21,Name ="Karacabey	",Code =  "224" }  ,
                new District()  {Id=225 ,   CityId =21,Name ="Keles	",Code =  "224" }  ,
                new District()  {Id=226 ,   CityId =21,Name ="Kestel	",Code =  "224" }  ,
                new District()  {Id=227 ,   CityId =21,Name ="Mudanya	" ,   Code =  "224" }  ,
                new District()  {Id=228 ,   CityId =21,Name ="Mustafakemalpaşa",Code =  "224" }  ,
                new District()  {Id=229 ,   CityId =21,Name ="Nilüfer	" ,   Code =  "224" }  ,
                new District()  {Id=230 ,   CityId =21,Name ="Orhaneli",Code =  "224" }  ,
                new District()  {Id=231 ,   CityId =21,Name ="Orhangazi	",Code =  "224" }  ,
                new District()  {Id=232 ,   CityId =21,Name ="Osmangazi	",Code =  "224" }  ,
                new District()  {Id=233 ,   CityId =21,Name ="Yenişehir	",Code =  "224" }  ,
                new District()  {Id=234 ,   CityId =21,Name ="Yıldırım",Code =  "224" }  ,
                new District()  {Id=235 ,   CityId =22,Name ="Ayvacık	" ,   Code =  "286" }  ,
                new District()  {Id=236 ,   CityId =22,Name ="Bayramiç",Code =  "286" }  ,
                new District()  {Id=237 ,   CityId =22,Name ="Biga",Code =  "286" }  ,
                new District()  {Id=238 ,   CityId =22,Name ="Bozcaada",Code =  "286" }  ,
                new District()  {Id=239 ,   CityId =22,Name ="Çan	" ,   Code =  "286" }  ,
                new District()  {Id=240 ,   CityId =22,Name ="Eceabat	" ,   Code =  "286" }  ,
                new District()  {Id=241 ,   CityId =22,Name ="Ezine	",Code =  "286" }  ,
                new District()  {Id=242 ,   CityId =22,Name ="Gelibolu",Code =  "286" }  ,
                new District()  {Id=243 ,   CityId =22,Name ="Gökçeada",Code =  "286" }  ,
                new District()  {Id=244 ,   CityId =22,Name ="Lapseki	" ,   Code =  "286" }  ,
                new District()  {Id=245 ,   CityId =22,Name ="Merkez	",Code =  "286" }  ,
                new District()  {Id=246 ,   CityId =22,Name ="Yenice	",Code =  "286" }  ,
                new District()  {Id=247 ,   CityId =23,Name ="Atkaracalar	" ,   Code =  "376" }  ,
                new District()  {Id=248 ,   CityId =23,Name ="Bayramören	",Code =  "376" }  ,
                new District()  {Id=249 ,   CityId =23,Name ="Çerkeş	",Code =  "376" }  ,
                new District()  {Id=250 ,   CityId =23,Name ="Eldivan	" ,   Code =  "376" }  ,
                new District()  {Id=251 ,   CityId =23,Name ="Ilgaz	",Code =  "376" }  ,
                new District()  {Id=252 ,   CityId =23,Name ="Kızılırmak	",Code =  "376" }  ,
                new District()  {Id=253 ,   CityId =23,Name ="Korgun	",Code =  "376" }  ,
                new District()  {Id=254 ,   CityId =23,Name ="Kurşunlu",Code =  "376" }  ,
                new District()  {Id=255 ,   CityId =23,Name ="Merkez	",Code =  "376" }  ,
                new District()  {Id=256 ,   CityId =23,Name ="Orta",Code =  "376" }  ,
                new District()  {Id=257 ,   CityId =23,Name ="Şabanözü",Code =  "376" }  ,
                new District()  {Id=258 ,   CityId =23,Name ="Yapraklı",Code =  "376" }  ,
                new District()  {Id=259 ,   CityId =24,Name ="Alaca	",Code =  "364" }  ,
                new District()  {Id=260 ,   CityId =24,Name ="Bayat	",Code =  "364" }  ,
                new District()  {Id=261 ,   CityId =24,Name ="Boğazkale	",Code =  "364" }  ,
                new District()  {Id=262 ,   CityId =24,Name ="Dodurga	" ,   Code =  "364" }  ,
                new District()  {Id=263 ,   CityId =24,Name ="İskilip	" ,   Code =  "364" }  ,
                new District()  {Id=264 ,   CityId =24,Name ="Kargı	",Code =  "364" }  ,
                new District()  {Id=265 ,   CityId =24,Name ="Laçin	",Code =  "364" }  ,
                new District()  {Id=266 ,   CityId =24,Name ="Mecitözü",Code =  "364" }  ,
                new District()  {Id=267 ,   CityId =24,Name ="Merkez	",Code =  "364" }  ,
                new District()  {Id=268 ,   CityId =24,Name ="Oğuzlar	" ,   Code =  "364" }  ,
                new District()  {Id=269 ,   CityId =24,Name ="Ortaköy	" ,   Code =  "364" }  ,
                new District()  {Id=270 ,   CityId =24,Name ="Osmancık",Code =  "364" }  ,
                new District()  {Id=271 ,   CityId =24,Name ="Sungurlu",Code =  "364" }  ,
                new District()  {Id=272 ,   CityId =24,Name ="Uğurludağ	",Code =  "364" }  ,
                new District()  {Id=273 ,   CityId =25,Name ="Acıpayam",Code =  "258" }  ,
                new District()  {Id=274 ,   CityId =25,Name ="Babadağ	" ,   Code =  "258" }  ,
                new District()  {Id=275 ,   CityId =25,Name ="Baklan	",Code =  "258" }  ,
                new District()  {Id=276 ,   CityId =25,Name ="Bekilli	" ,   Code =  "258" }  ,
                new District()  {Id=277 ,   CityId =25,Name ="Beyağaç	" ,   Code =  "258" }  ,
                new District()  {Id=278 ,   CityId =25,Name ="Bozkurt	" ,   Code =  "258" }  ,
                new District()  {Id=279 ,   CityId =25,Name ="Buldan	",Code =  "258" }  ,
                new District()  {Id=280 ,   CityId =25,Name ="Çal	" ,   Code =  "258" }  ,
                new District()  {Id=281 ,   CityId =25,Name ="Çameli	",Code =  "258" }  ,
                new District()  {Id=282 ,   CityId =25,Name ="Çardak	",Code =  "258" }  ,
                new District()  {Id=283 ,   CityId =25,Name ="Çivril	",Code =  "258" }  ,
                new District()  {Id=284 ,   CityId =25,Name ="Güney	",Code =  "258" }  ,
                new District()  {Id=285 ,   CityId =25,Name ="Honaz	",Code =  "258" }  ,
                new District()  {Id=286 ,   CityId =25,Name ="Kale",Code =  "258" }  ,
                new District()  {Id=287 ,   CityId =25,Name ="Merkezefendi",Code =  "258" }  ,
                new District()  {Id=288 ,   CityId =25,Name ="Pamukkale	",Code =  "258" }  ,
                new District()  {Id=289 ,   CityId =25,Name ="Sarayköy",Code =  "258" }  ,
                new District()  {Id=290 ,   CityId =25,Name ="Serinhisar	",Code =  "258" }  ,
                new District()  {Id=291 ,   CityId =25,Name ="Tavas	",Code =  "258" }  ,
                new District()  {Id=292 ,   CityId =26,Name ="Bağlar	",Code =  "412" }  ,
                new District()  {Id=293 ,   CityId =26,Name ="Bismil	",Code =  "412" }  ,
                new District()  {Id=294 ,   CityId =26,Name ="Çermik	",Code =  "412" }  ,
                new District()  {Id=295 ,   CityId =26,Name ="Çınar	",Code =  "412" }  ,
                new District()  {Id=296 ,   CityId =26,Name ="Çüngüş	",Code =  "412" }  ,
                new District()  {Id=297 ,   CityId =26,Name ="Dicle	",Code =  "412" }  ,
                new District()  {Id=298 ,   CityId =26,Name ="Eğil",Code =  "412" }  ,
                new District()  {Id=299 ,   CityId =26,Name ="Ergani	",Code =  "412" }  ,
                new District()  {Id=300 ,   CityId =26,Name ="Hani",Code =  "412" }  ,
                new District()  {Id=301 ,   CityId =26,Name ="Hazro	",Code =  "412" }  ,
                new District()  {Id=302 ,   CityId =26,Name ="Kayapınar	",Code =  "412" }  ,
                new District()  {Id=303 ,   CityId =26,Name ="Kocaköy	" ,   Code =  "412" }  ,
                new District()  {Id=304 ,   CityId =26,Name ="Kulp",Code =  "412" }  ,
                new District()  {Id=305 ,   CityId =26,Name ="Lice",Code =  "412" }  ,
                new District()  {Id=306 ,   CityId =26,Name ="Silvan	",Code =  "412" }  ,
                new District()  {Id=307 ,   CityId =26,Name ="Sur	" ,   Code =  "412" }  ,
                new District()  {Id=308 ,   CityId =26,Name ="Yenişehir	",Code =  "412" }  ,
                new District()  {Id=309 ,   CityId =27,Name ="Akçakoca",Code =  "380" }  ,
                new District()  {Id=310 ,   CityId =27,Name ="Çilimli	" ,   Code =  "380" }  ,
                new District()  {Id=311 ,   CityId =27,Name ="Cumayeri",Code =  "380" }  ,
                new District()  {Id=312 ,   CityId =27,Name ="Gölyaka	" ,   Code =  "380" }  ,
                new District()  {Id=313 ,   CityId =27,Name ="Gümüşova",Code =  "380" }  ,
                new District()  {Id=314 ,   CityId =27,Name ="Kaynaşlı",Code =  "380" }  ,
                new District()  {Id=315 ,   CityId =27,Name ="Merkez	",Code =  "380" }  ,
                new District()  {Id=316 ,   CityId =27,Name ="Yığılca	" ,   Code =  "380" }  ,
                new District()  {Id=317 ,   CityId =28,Name ="Enez",Code =  "284" }  ,
                new District()  {Id=318 ,   CityId =28,Name ="Havsa	",Code =  "284" }  ,
                new District()  {Id=319 ,   CityId =28,Name ="İpsala	",Code =  "284" }  ,
                new District()  {Id=320 ,   CityId =28,Name ="Keşan	",Code =  "284" }  ,
                new District()  {Id=321 ,   CityId =28,Name ="Lalapaşa",Code =  "284" }  ,
                new District()  {Id=322 ,   CityId =28,Name ="Meriç	",Code =  "284" }  ,
                new District()  {Id=323 ,   CityId =28,Name ="Merkez	",Code =  "284" }  ,
                new District()  {Id=324 ,   CityId =28,Name ="Süloğlu	" ,   Code =  "284" }  ,
                new District()  {Id=325 ,   CityId =28,Name ="Uzunköprü	",Code =  "284" }  ,
                new District()  {Id=326 ,   CityId =29,Name ="Ağın",Code =  "424" }  ,
                new District()  {Id=327 ,   CityId =29,Name ="Alacakaya	",Code =  "424" }  ,
                new District()  {Id=328 ,   CityId =29,Name ="Arıcak	",Code =  "424" }  ,
                new District()  {Id=329 ,   CityId =29,Name ="Baskil	",Code =  "424" }  ,
                new District()  {Id=330 ,   CityId =29,Name ="Karakoçan	",Code =  "424" }  ,
                new District()  {Id=331 ,   CityId =29,Name ="Keban	",Code =  "424" }  ,
                new District()  {Id=332 ,   CityId =29,Name ="Kovancılar	",Code =  "424" }  ,
                new District()  {Id=333 ,   CityId =29,Name ="Maden	",Code =  "424" }  ,
                new District()  {Id=334 ,   CityId =29,Name ="Merkez	",Code =  "424" }  ,
                new District()  {Id=335 ,   CityId =29,Name ="Palu",Code =  "424" }  ,
                new District()  {Id=336 ,   CityId =29,Name ="Sivrice	" ,   Code =  "424" }  ,
                new District()  {Id=337 ,   CityId =30,Name ="Çayırlı	" ,   Code =  "446" }  ,
                new District()  {Id=338 ,   CityId =30,Name ="İliç",Code =  "446" }  ,
                new District()  {Id=339 ,   CityId =30,Name ="Kemah	",Code =  "446" }  ,
                new District()  {Id=340 ,   CityId =30,Name ="Kemaliye",Code =  "446" }  ,
                new District()  {Id=341 ,   CityId =30,Name ="Merkez	",Code =  "446" }  ,
                new District()  {Id=342 ,   CityId =30,Name ="Otlukbeli	",Code =  "446" }  ,
                new District()  {Id=343 ,   CityId =30,Name ="Refahiye",Code =  "446" }  ,
                new District()  {Id=344 ,   CityId =30,Name ="Tercan	",Code =  "446" }  ,
                new District()  {Id=345 ,   CityId =30,Name ="Üzümlü	",Code =  "446" }  ,
                new District()  {Id=346 ,   CityId =31,Name ="Aşkale	",Code =  "442" }  ,
                new District()  {Id=347 ,   CityId =31,Name ="Aziziye	" ,   Code =  "442" }  ,
                new District()  {Id=348 ,   CityId =31,Name ="Çat	" ,   Code =  "442" }  ,
                new District()  {Id=349 ,   CityId =31,Name ="Hınıs	",Code =  "442" }  ,
                new District()  {Id=350 ,   CityId =31,Name ="Horasan	" ,   Code =  "442" }  ,
                new District()  {Id=351 ,   CityId =31,Name ="İspir	",Code =  "442" }  ,
                new District()  {Id=352 ,   CityId =31,Name ="Karaçoban	",Code =  "442" }  ,
                new District()  {Id=353 ,   CityId =31,Name ="Karayazı",Code =  "442" }  ,
                new District()  {Id=354 ,   CityId =31,Name ="Köprüköy",Code =  "442" }  ,
                new District()  {Id=355 ,   CityId =31,Name ="Narman	",Code =  "442" }  ,
                new District()  {Id=356 ,   CityId =31,Name ="Oltu",Code =  "442" }  ,
                new District()  {Id=357 ,   CityId =31,Name ="Olur",Code =  "442" }  ,
                new District()  {Id=358 ,   CityId =31,Name ="Palandöken	",Code =  "442" }  ,
                new District()  {Id=359 ,   CityId =31,Name ="Pasinler",Code =  "442" }  ,
                new District()  {Id=360 ,   CityId =31,Name ="Pazaryolu	",Code =  "442" }  ,
                new District()  {Id=361 ,   CityId =31,Name ="Şenkaya	" ,   Code =  "442" }  ,
                new District()  {Id=362 ,   CityId =31,Name ="Tekman	",Code =  "442" }  ,
                new District()  {Id=363 ,   CityId =31,Name ="Tortum	",Code =  "442" }  ,
                new District()  {Id=364 ,   CityId =31,Name ="Uzundere",Code =  "442" }  ,
                new District()  {Id=365 ,   CityId =31,Name ="Yakutiye",Code =  "442" }  ,
                new District()  {Id=366 ,   CityId =32,Name ="Alpu",Code =  "222" }  ,
                new District()  {Id=367 ,   CityId =32,Name ="Beylikova	",Code =  "222" }  ,
                new District()  {Id=368 ,   CityId =32,Name ="Çifteler",Code =  "222" }  ,
                new District()  {Id=369 ,   CityId =32,Name ="Günyüzü	" ,   Code =  "222" }  ,
                new District()  {Id=370 ,   CityId =32,Name ="Han	" ,   Code =  "222" }  ,
                new District()  {Id=371 ,   CityId =32,Name ="İnönü	",Code =  "222" }  ,
                new District()  {Id=372 ,   CityId =32,Name ="Mahmudiye	",Code =  "222" }  ,
                new District()  {Id=373 ,   CityId =32,Name ="Mihalgazi	",Code =  "222" }  ,
                new District()  {Id=374 ,   CityId =32,Name ="Mihalıççık	",Code =  "222" }  ,
                new District()  {Id=375 ,   CityId =32,Name ="Odunpazarı	",Code =  "222" }  ,
                new District()  {Id=376 ,   CityId =32,Name ="Sarıcakaya	",Code =  "222" }  ,
                new District()  {Id=377 ,   CityId =32,Name ="Seyitgazi	",Code =  "222" }  ,
                new District()  {Id=378 ,   CityId =32,Name ="Sivrihisar	",Code =  "222" }  ,
                new District()  {Id=379 ,   CityId =32,Name ="Tepebaşı",Code =  "222" }  ,
                new District()  {Id=380 ,   CityId =33,Name ="Araban	",Code =  "342" }  ,
                new District()  {Id=381 ,   CityId =33,Name ="İslahiye",Code =  "342" }  ,
                new District()  {Id=382 ,   CityId =33,Name ="Karkamış",Code =  "342" }  ,
                new District()  {Id=383 ,   CityId =33,Name ="Nizip	",Code =  "342" }  ,
                new District()  {Id=384 ,   CityId =33,Name ="Nurdağı	" ,   Code =  "342" }  ,
                new District()  {Id=385 ,   CityId =33,Name ="Oğuzeli	" ,   Code =  "342" }  ,
                new District()  {Id=386 ,   CityId =33,Name ="Şahinbey",Code =  "342" }  ,
                new District()  {Id=387 ,   CityId =33,Name ="Şehitkamil	",Code =  "342" }  ,
                new District()  {Id=388 ,   CityId =33,Name ="Yavuzeli",Code =  "342" }  ,
                new District()  {Id=389 ,   CityId =34,Name ="Alucra	",Code =  "454" }  ,
                new District()  {Id=390 ,   CityId =34,Name ="Bulancak",Code =  "454" }  ,
                new District()  {Id=391 ,   CityId =34,Name ="Çamoluk	" ,   Code =  "454" }  ,
                new District()  {Id=392 ,   CityId =34,Name ="Çanakçı	" ,   Code =  "454" }  ,
                new District()  {Id=393 ,   CityId =34,Name ="Dereli	",Code =  "454" }  ,
                new District()  {Id=394 ,   CityId =34,Name ="Doğankent	",Code =  "454" }  ,
                new District()  {Id=395 ,   CityId =34,Name ="Espiye	",Code =  "454" }  ,
                new District()  {Id=396 ,   CityId =34,Name ="Eynesil	" ,   Code =  "454" }  ,
                new District()  {Id=397 ,   CityId =34,Name ="Görele	",Code =  "454" }  ,
                new District()  {Id=398 ,   CityId =34,Name ="Güce",Code =  "454" }  ,
                new District()  {Id=399 ,   CityId =34,Name ="Keşap	",Code =  "454" }  ,
                new District()  {Id=400 ,   CityId =34,Name ="Merkez	",Code =  "454" }  ,
                new District()  {Id=401 ,   CityId =34,Name ="Piraziz	" ,   Code =  "454" }  ,
                new District()  {Id=402 ,   CityId =34,Name ="Şebinkarahisar	",Code =  "454" }  ,
                new District()  {Id=403 ,   CityId =34,Name ="Tirebolu",Code =  "454" }  ,
                new District()  {Id=404 ,   CityId =34,Name ="Yağlıdere	",Code =  "454" }  ,
                new District()  {Id=405 ,   CityId =35,Name ="Kelkit	",Code =  "456" }  ,
                new District()  {Id=406 ,   CityId =35,Name ="Köse",Code =  "456" }  ,
                new District()  {Id=407 ,   CityId =35,Name ="Kürtün	",Code =  "456" }  ,
                new District()  {Id=408 ,   CityId =35,Name ="Merkez	",Code =  "456" }  ,
                new District()  {Id=409 ,   CityId =35,Name ="Şiran	",Code =  "456" }  ,
                new District()  {Id=410 ,   CityId =35,Name ="Torul	",Code =  "456" }  ,
                new District()  {Id=411 ,   CityId =36,Name ="Çukurca	" ,   Code =  "438" }  ,
                new District()  {Id=412 ,   CityId =36,Name ="Derecik	" ,   Code =  "438" }  ,
                new District()  {Id=413 ,   CityId =36,Name ="Merkez	",Code =  "438" }  ,
                new District()  {Id=414 ,   CityId =36,Name ="Şemdinli",Code =  "438" }  ,
                new District()  {Id=415 ,   CityId =36,Name ="Yüksekova	",Code =  "438" }  ,
                new District()  {Id=416 ,   CityId =37,Name ="Altınözü",Code =  "326" }  ,
                new District()  {Id=417 ,   CityId =37,Name ="Antakya	" ,   Code =  "326" }  ,
                new District()  {Id=418 ,   CityId =37,Name ="Arsuz	",Code =  "326" }  ,
                new District()  {Id=419 ,   CityId =37,Name ="Belen	",Code =  "326" }  ,
                new District()  {Id=420 ,   CityId =37,Name ="Defne	",Code =  "326" }  ,
                new District()  {Id=421 ,   CityId =37,Name ="Dörtyol	" ,   Code =  "326" }  ,
                new District()  {Id=422 ,   CityId =37,Name ="Erzin	",Code =  "326" }  ,
                new District()  {Id=423 ,   CityId =37,Name ="Hassa	",Code =  "326" }  ,
                new District()  {Id=424 ,   CityId =37,Name ="İskenderun	",Code =  "326" }  ,
                new District()  {Id=425 ,   CityId =37,Name ="Kırıkhan",Code =  "326" }  ,
                new District()  {Id=426 ,   CityId =37,Name ="Kumlu	",Code =  "326" }  ,
                new District()  {Id=427 ,   CityId =37,Name ="Payas	",Code =  "326" }  ,
                new District()  {Id=428 ,   CityId =37,Name ="Reyhanlı",Code =  "326" }  ,
                new District()  {Id=429 ,   CityId =37,Name ="Samandağ",Code =  "326" }  ,
                new District()  {Id=430 ,   CityId =37,Name ="Yayladağı	",Code =  "326" }  ,
                new District()  {Id=431 ,   CityId =38,Name ="Aralık	",Code =  "476" }  ,
                new District()  {Id=432 ,   CityId =38,Name ="Karakoyunlu	" ,   Code =  "476" }  ,
                new District()  {Id=433 ,   CityId =38,Name ="Merkez	",Code =  "476" }  ,
                new District()  {Id=434 ,   CityId =38,Name ="Tuzluca	" ,   Code =  "476" }  ,
                new District()  {Id=435 ,   CityId =39,Name ="Aksu",Code =  "246" }  ,
                new District()  {Id=436 ,   CityId =39,Name ="Atabey	",Code =  "246" }  ,
                new District()  {Id=437 ,   CityId =39,Name ="Eğirdir	" ,   Code =  "246" }  ,
                new District()  {Id=438 ,   CityId =39,Name ="Gelendost	",Code =  "246" }  ,
                new District()  {Id=439 ,   CityId =39,Name ="Gönen	",Code =  "246" }  ,
                new District()  {Id=440 ,   CityId =39,Name ="Keçiborlu	",Code =  "246" }  ,
                new District()  {Id=441 ,   CityId =39,Name ="Merkez	",Code =  "246" }  ,
                new District()  {Id=442 ,   CityId =39,Name ="Şarkikaraağaç	",Code =  "246" }  ,
                new District()  {Id=443 ,   CityId =39,Name ="Senirkent	",Code =  "246" }  ,
                new District()  {Id=444 ,   CityId =39,Name ="Sütçüler",Code =  "246" }  ,
                new District()  {Id=445 ,   CityId =39,Name ="Uluborlu",Code =  "246" }  ,
                new District()  {Id=446 ,   CityId =39,Name ="Yalvaç	",Code =  "246" }  ,
                new District()  {Id=447 ,   CityId =39,Name ="Yenişarbademli	",Code =  "246" }  ,
                new District()  {Id=448 ,   CityId =40,Name ="Akdeniz	" ,   Code =  "324" }  ,
                new District()  {Id=449 ,   CityId =40,Name ="Anamur	",Code =  "324" }  ,
                new District()  {Id=450 ,   CityId =40,Name ="Aydıncık",Code =  "324" }  ,
                new District()  {Id=451 ,   CityId =40,Name ="Bozyazı	" ,   Code =  "324" }  ,
                new District()  {Id=452 ,   CityId =40,Name ="Çamlıyayla	",Code =  "324" }  ,
                new District()  {Id=453 ,   CityId =40,Name ="Erdemli	" ,   Code =  "324" }  ,
                new District()  {Id=454 ,   CityId =40,Name ="Gülnar	",Code =  "324" }  ,
                new District()  {Id=455 ,   CityId =40,Name ="Mezitli	" ,   Code =  "324" }  ,
                new District()  {Id=456 ,   CityId =40,Name ="Mut	" ,   Code =  "324" }  ,
                new District()  {Id=457 ,   CityId =40,Name ="Silifke	" ,   Code =  "324" }  ,
                new District()  {Id=458 ,   CityId =40,Name ="Tarsus	",Code =  "324" }  ,
                new District()  {Id=459 ,   CityId =40,Name ="Toroslar",Code =  "324" }  ,
                new District()  {Id=460 ,   CityId =40,Name ="Yenişehir	",Code =  "324" }  ,
                new District()  {Id=461 ,   CityId =41,Name ="Arnavutköy	",Code =  "212" }  ,
                new District()  {Id=462 ,   CityId =41,Name ="Avcılar	" ,   Code =  "212" }  ,
                new District()  {Id=463 ,   CityId =41,Name ="Bağcılar",Code =  "212" }  ,
                new District()  {Id=464 ,   CityId =41,Name ="Bahçelievler",Code =  "212" }  ,
                new District()  {Id=465 ,   CityId =41,Name ="Bakırköy",Code =  "212" }  ,
                new District()  {Id=466 ,   CityId =41,Name ="Başakşehir	",Code =  "212" }  ,
                new District()  {Id=467 ,   CityId =41,Name ="Bayrampaşa	",Code =  "212" }  ,
                new District()  {Id=468 ,   CityId =41,Name ="Beşiktaş",Code =  "212" }  ,
                new District()  {Id=469 ,   CityId =41,Name ="Beylikdüzü	",Code =  "212" }  ,
                new District()  {Id=470 ,   CityId =41,Name ="Beyoğlu	" ,   Code =  "212" }  ,
                new District()  {Id=471 ,   CityId =41,Name ="Büyükçekmece",Code =  "212" }  ,
                new District()  {Id=472 ,   CityId =41,Name ="Çatalca	" ,   Code =  "212" }  ,
                new District()  {Id=473 ,   CityId =41,Name ="Esenler	" ,   Code =  "212" }  ,
                new District()  {Id=474 ,   CityId =41,Name ="Esenyurt",Code =  "212" }  ,
                new District()  {Id=475 ,   CityId =41,Name ="Eyüp",Code =  "212" }  ,
                new District()  {Id=476 ,   CityId =41,Name ="Fatih	",Code =  "212" }  ,
                new District()  {Id=477 ,   CityId =41,Name ="Gaziosmanpaşa	",Code =  "212" }  ,
                new District()  {Id=478 ,   CityId =41,Name ="Güngören",Code =  "212" }  ,
                new District()  {Id=479 ,   CityId =41,Name ="Kağıthane	",Code =  "212" }  ,
                new District()  {Id=480 ,   CityId =41,Name ="Küçükçekmece",Code =  "212" }  ,
                new District()  {Id=481 ,   CityId =41,Name ="Sarıyer	" ,   Code =  "212" }  ,
                new District()  {Id=482 ,   CityId =41,Name ="Silivri	" ,   Code =  "212" }  ,
                new District()  {Id=483 ,   CityId =41,Name ="Sultangazi	",Code =  "212" }  ,
                new District()  {Id=484 ,   CityId =41,Name ="Şişli	",Code =  "212" }  ,
                new District()  {Id=485 ,   CityId =41,Name ="Zeytinburnu	" ,   Code =  "212" }  ,
                new District()  {Id=486 ,   CityId =42,Name ="Adalar	",Code =  "216" }  ,
                new District()  {Id=487 ,   CityId =42,Name ="Ataşehir",Code =  "216" }  ,
                new District()  {Id=488 ,   CityId =42,Name ="Beykoz	",Code =  "216" }  ,
                new District()  {Id=489 ,   CityId =42,Name ="Çekmeköy",Code =  "216" }  ,
                new District()  {Id=490 ,   CityId =42,Name ="Kadıköy	" ,   Code =  "216" }  ,
                new District()  {Id=491 ,   CityId =42,Name ="Kartal	",Code =  "216" }  ,
                new District()  {Id=492 ,   CityId =42,Name ="Maltepe	" ,   Code =  "216" }  ,
                new District()  {Id=493 ,   CityId =42,Name ="Pendik	",Code =  "216" }  ,
                new District()  {Id=494 ,   CityId =42,Name ="Sancaktepe	",Code =  "216" }  ,
                new District()  {Id=495 ,   CityId =42,Name ="Sultanbeyli	" ,   Code =  "216" }  ,
                new District()  {Id=496 ,   CityId =42,Name ="Şile",Code =  "216" }  ,
                new District()  {Id=497 ,   CityId =42,Name ="Tuzla	",Code =  "216" }  ,
                new District()  {Id=498 ,   CityId =42,Name ="Ümraniye",Code =  "216" }  ,
                new District()  {Id=499 ,   CityId =42,Name ="Üsküdar	" ,   Code =  "216" }  ,
                new District()  {Id=500 ,   CityId =43,Name ="Aliağa	",Code =  "232" }  ,
                new District()  {Id=501 ,   CityId =43,Name ="Balçova	" ,   Code =  "232" }  ,
                new District()  {Id=502 ,   CityId =43,Name ="Bayındır",Code =  "232" }  ,
                new District()  {Id=503 ,   CityId =43,Name ="Bayraklı",Code =  "232" }  ,
                new District()  {Id=504 ,   CityId =43,Name ="Bergama	" ,   Code =  "232" }  ,
                new District()  {Id=505 ,   CityId =43,Name ="Beydağ	",Code =  "232" }  ,
                new District()  {Id=506 ,   CityId =43,Name ="Bornova	" ,   Code =  "232" }  ,
                new District()  {Id=507 ,   CityId =43,Name ="Buca",Code =  "232" }  ,
                new District()  {Id=508 ,   CityId =43,Name ="Çeşme	",Code =  "232" }  ,
                new District()  {Id=509 ,   CityId =43,Name ="Çiğli	",Code =  "232" }  ,
                new District()  {Id=510 ,   CityId =43,Name ="Dikili	",Code =  "232" }  ,
                new District()  {Id=511 ,   CityId =43,Name ="Foça",Code =  "232" }  ,
                new District()  {Id=512 ,   CityId =43,Name ="Gaziemir",Code =  "232" }  ,
                new District()  {Id=513 ,   CityId =43,Name ="Güzelbahçe	",Code =  "232" }  ,
                new District()  {Id=514 ,   CityId =43,Name ="Karabağlar	",Code =  "232" }  ,
                new District()  {Id=515 ,   CityId =43,Name ="Karaburun	",Code =  "232" }  ,
                new District()  {Id=516 ,   CityId =43,Name ="Karşıyaka	",Code =  "232" }  ,
                new District()  {Id=517 ,   CityId =43,Name ="Kemalpaşa	",Code =  "232" }  ,
                new District()  {Id=518 ,   CityId =43,Name ="Kınık	",Code =  "232" }  ,
                new District()  {Id=519 ,   CityId =43,Name ="Kiraz	",Code =  "232" }  ,
                new District()  {Id=520 ,   CityId =43,Name ="Konak	",Code =  "232" }  ,
                new District()  {Id=521 ,   CityId =43,Name ="Menderes",Code =  "232" }  ,
                new District()  {Id=522 ,   CityId =43,Name ="Menemen	" ,   Code =  "232" }  ,
                new District()  {Id=523 ,   CityId =43,Name ="Narlıdere	",Code =  "232" }  ,
                new District()  {Id=524 ,   CityId =43,Name ="Ödemiş	",Code =  "232" }  ,
                new District()  {Id=525 ,   CityId =43,Name ="Seferihisar	" ,   Code =  "232" }  ,
                new District()  {Id=526 ,   CityId =43,Name ="Selçuk	",Code =  "232" }  ,
                new District()  {Id=527 ,   CityId =43,Name ="Tire",Code =  "232" }  ,
                new District()  {Id=528 ,   CityId =43,Name ="Torbalı	" ,   Code =  "232" }  ,
                new District()  {Id=529 ,   CityId =43,Name ="Urla",Code =  "232" }  ,
                new District()  {Id=530 ,   CityId =44,Name ="Eflani	",Code =  "370" }  ,
                new District()  {Id=531 ,   CityId =44,Name ="Eskipazar	",Code =  "370" }  ,
                new District()  {Id=532 ,   CityId =44,Name ="Merkez	",Code =  "370" }  ,
                new District()  {Id=533 ,   CityId =44,Name ="Ovacık	",Code =  "370" }  ,
                new District()  {Id=534 ,   CityId =44,Name ="Safranbolu	",Code =  "370" }  ,
                new District()  {Id=535 ,   CityId =44,Name ="Yenice	",Code =  "370" }  ,
                new District()  {Id=536 ,   CityId =45,Name ="Ayrancı	" ,   Code =  "338" }  ,
                new District()  {Id=537 ,   CityId =45,Name ="Başyayla",Code =  "338" }  ,
                new District()  {Id=538 ,   CityId =45,Name ="Ermenek	" ,   Code =  "338" }  ,
                new District()  {Id=539 ,   CityId =45,Name ="Kazımkarabekir	",Code =  "338" }  ,
                new District()  {Id=540 ,   CityId =45,Name ="Merkez	",Code =  "338" }  ,
                new District()  {Id=541 ,   CityId =45,Name ="Sarıveliler	" ,   Code =  "338" }  ,
                new District()  {Id=542 ,   CityId =46,Name ="Akyaka	",Code =  "474" }  ,
                new District()  {Id=543 ,   CityId =46,Name ="Arpaçay	" ,   Code =  "474" }  ,
                new District()  {Id=544 ,   CityId =46,Name ="Digor	",Code =  "474" }  ,
                new District()  {Id=545 ,   CityId =46,Name ="Kağızman",Code =  "474" }  ,
                new District()  {Id=546 ,   CityId =46,Name ="Merkez	",Code =  "474" }  ,
                new District()  {Id=547 ,   CityId =46,Name ="Sarıkamış	",Code =  "474" }  ,
                new District()  {Id=548 ,   CityId =46,Name ="Selim	",Code =  "474" }  ,
                new District()  {Id=549 ,   CityId =46,Name ="Susuz	",Code =  "474" }  ,
                new District()  {Id=550 ,   CityId =47,Name ="Abana	",Code =  "366" }  ,
                new District()  {Id=551 ,   CityId =47,Name ="Ağlı",Code =  "366" }  ,
                new District()  {Id=552 ,   CityId =47,Name ="Araç",Code =  "366" }  ,
                new District()  {Id=553 ,   CityId =47,Name ="Azdavay	" ,   Code =  "366" }  ,
                new District()  {Id=554 ,   CityId =47,Name ="Bozkurt	" ,   Code =  "366" }  ,
                new District()  {Id=555 ,   CityId =47,Name ="Çatalzeytin	" ,   Code =  "366" }  ,
                new District()  {Id=556 ,   CityId =47,Name ="Cide",Code =  "366" }  ,
                new District()  {Id=557 ,   CityId =47,Name ="Daday	",Code =  "366" }  ,
                new District()  {Id=558 ,   CityId =47,Name ="Devrekani	",Code =  "366" }  ,
                new District()  {Id=559 ,   CityId =47,Name ="Doğanyurt	",Code =  "366" }  ,
                new District()  {Id=560 ,   CityId =47,Name ="Hanönü	",Code =  "366" }  ,
                new District()  {Id=561 ,   CityId =47,Name ="İhsangazi	",Code =  "366" }  ,
                new District()  {Id=562 ,   CityId =47,Name ="İnebolu	" ,   Code =  "366" }  ,
                new District()  {Id=563 ,   CityId =47,Name ="Küre",Code =  "366" }  ,
                new District()  {Id=564 ,   CityId =47,Name ="Merkez	",Code =  "366" }  ,
                new District()  {Id=565 ,   CityId =47,Name ="Pınarbaşı	",Code =  "366" }  ,
                new District()  {Id=566 ,   CityId =47,Name ="Şenpazar",Code =  "366" }  ,
                new District()  {Id=567 ,   CityId =47,Name ="Seydiler",Code =  "366" }  ,
                new District()  {Id=568 ,   CityId =47,Name ="Taşköprü",Code =  "366" }  ,
                new District()  {Id=569 ,   CityId =47,Name ="Tosya	",Code =  "366" }  ,
                new District()  {Id=570 ,   CityId =48,Name ="Akkışla	" ,   Code =  "352" }  ,
                new District()  {Id=571 ,   CityId =48,Name ="Bünyan	",Code =  "352" }  ,
                new District()  {Id=572 ,   CityId =48,Name ="Develi	",Code =  "352" }  ,
                new District()  {Id=573 ,   CityId =48,Name ="Felahiye",Code =  "352" }  ,
                new District()  {Id=574 ,   CityId =48,Name ="Hacılar	" ,   Code =  "352" }  ,
                new District()  {Id=575 ,   CityId =48,Name ="İncesu	",Code =  "352" }  ,
                new District()  {Id=576 ,   CityId =48,Name ="Kocasinan	",Code =  "352" }  ,
                new District()  {Id=577 ,   CityId =48,Name ="Melikgazi	",Code =  "352" }  ,
                new District()  {Id=578 ,   CityId =48,Name ="Özvatan	" ,   Code =  "352" }  ,
                new District()  {Id=579 ,   CityId =48,Name ="Pınarbaşı	",Code =  "352" }  ,
                new District()  {Id=580 ,   CityId =48,Name ="Sarıoğlan	",Code =  "352" }  ,
                new District()  {Id=581 ,   CityId =48,Name ="Sarız	",Code =  "352" }  ,
                new District()  {Id=582 ,   CityId =48,Name ="Talas	",Code =  "352" }  ,
                new District()  {Id=583 ,   CityId =48,Name ="Tomarza	" ,   Code =  "352" }  ,
                new District()  {Id=584 ,   CityId =48,Name ="Yahyalı	" ,   Code =  "352" }  ,
                new District()  {Id=585 ,   CityId =48,Name ="Yeşilhisar	",Code =  "352" }  ,
                new District()  {Id=586 ,   CityId =49,Name ="Bahşılı	" ,   Code =  "318" }  ,
                new District()  {Id=587 ,   CityId =49,Name ="Balışeyh",Code =  "318" }  ,
                new District()  {Id=588 ,   CityId =49,Name ="Çelebi	",Code =  "318" }  ,
                new District()  {Id=589 ,   CityId =49,Name ="Delice	",Code =  "318" }  ,
                new District()  {Id=590 ,   CityId =49,Name ="Karakeçili	",Code =  "318" }  ,
                new District()  {Id=591 ,   CityId =49,Name ="Keskin	",Code =  "318" }  ,
                new District()  {Id=592 ,   CityId =49,Name ="Merkez	",Code =  "318" }  ,
                new District()  {Id=593 ,   CityId =49,Name ="Sulakyurt	",Code =  "318" }  ,
                new District()  {Id=594 ,   CityId =49,Name ="Yahşihan",Code =  "318" }  ,
                new District()  {Id=595 ,   CityId =50,Name ="Babaeski",Code =  "288" }  ,
                new District()  {Id=596 ,   CityId =50,Name ="Demirköy",Code =  "288" }  ,
                new District()  {Id=597 ,   CityId =50,Name ="Kofçaz	",Code =  "288" }  ,
                new District()  {Id=598 ,   CityId =50,Name ="Lüleburgaz	",Code =  "288" }  ,
                new District()  {Id=599 ,   CityId =50,Name ="Merkez	",Code =  "288" }  ,
                new District()  {Id=600 ,   CityId =50,Name ="Pehlivanköy	" ,   Code =  "288" }  ,
                new District()  {Id=601 ,   CityId =50,Name ="Pınarhisar	",Code =  "288" }  ,
                new District()  {Id=602 ,   CityId =50,Name ="Vize",Code =  "288" }  ,
                new District()  {Id=603 ,   CityId =51,Name ="Akçakent",Code =  "386" }  ,
                new District()  {Id=604 ,   CityId =51,Name ="Akpınar	" ,   Code =  "386" }  ,
                new District()  {Id=605 ,   CityId =51,Name ="Boztepe	" ,   Code =  "386" }  ,
                new District()  {Id=606 ,   CityId =51,Name ="Çiçekdağı	",Code =  "386" }  ,
                new District()  {Id=607 ,   CityId =51,Name ="Kaman	",Code =  "386" }  ,
                new District()  {Id=608 ,   CityId =51,Name ="Merkez	",Code =  "386" }  ,
                new District()  {Id=609 ,   CityId =51,Name ="Mucur	",Code =  "386" }  ,
                new District()  {Id=610 ,   CityId =52,Name ="Elbeyli	" ,   Code =  "348" }  ,
                new District()  {Id=611 ,   CityId =52,Name ="Merkez	",Code =  "348" }  ,
                new District()  {Id=612 ,   CityId =52,Name ="Musabeyli	",Code =  "348" }  ,
                new District()  {Id=613 ,   CityId =52,Name ="Polateli",Code =  "348" }  ,
                new District()  {Id=614 ,   CityId =53,Name ="Afşin	",Code =  "344" }  ,
                new District()  {Id=615 ,   CityId =53,Name ="Andırın	" ,   Code =  "344" }  ,
                new District()  {Id=616 ,   CityId =53,Name ="Çağlayancerit	",Code =  "344" }  ,
                new District()  {Id=617 ,   CityId =53,Name ="Dulkadiroğlu",Code =  "344" }  ,
                new District()  {Id=618 ,   CityId =53,Name ="Ekinözü	" ,   Code =  "344" }  ,
                new District()  {Id=619 ,   CityId =53,Name ="Elbistan",Code =  "344" }  ,
                new District()  {Id=620 ,   CityId =53,Name ="Göksun	",Code =  "344" }  ,
                new District()  {Id=621 ,   CityId =53,Name ="Nurhak	",Code =  "344" }  ,
                new District()  {Id=622 ,   CityId =53,Name ="Onikişubat	",Code =  "344" }  ,
                new District()  {Id=623 ,   CityId =53,Name ="Pazarcık",Code =  "344" }  ,
                new District()  {Id=624 ,   CityId =53,Name ="Türkoğlu",Code =  "344" }  ,
                new District()  {Id=625 ,   CityId =54,Name ="Başiskele	",Code =  "262" }  ,
                new District()  {Id=626 ,   CityId =54,Name ="Çayırova",Code =  "262" }  ,
                new District()  {Id=627 ,   CityId =54,Name ="Darıca	",Code =  "262" }  ,
                new District()  {Id=628 ,   CityId =54,Name ="Derince	" ,   Code =  "262" }  ,
                new District()  {Id=629 ,   CityId =54,Name ="Dilovası",Code =  "262" }  ,
                new District()  {Id=630 ,   CityId =54,Name ="Gebze	",Code =  "262" }  ,
                new District()  {Id=631 ,   CityId =54,Name ="Gölcük	",Code =  "262" }  ,
                new District()  {Id=632 ,   CityId =54,Name ="İzmit	",Code =  "262" }  ,
                new District()  {Id=633 ,   CityId =54,Name ="Kandıra	" ,   Code =  "262" }  ,
                new District()  {Id=634 ,   CityId =54,Name ="Karamürsel	",Code =  "262" }  ,
                new District()  {Id=635 ,   CityId =54,Name ="Kartepe	" ,   Code =  "262" }  ,
                new District()  {Id=636 ,   CityId =54,Name ="Körfez	",Code =  "262" }  ,
                new District()  {Id=637 ,   CityId =55,Name ="Ahırlı	",Code =  "332" }  ,
                new District()  {Id=638 ,   CityId =55,Name ="Akören	",Code =  "332" }  ,
                new District()  {Id=639 ,   CityId =55,Name ="Akşehir	" ,   Code =  "332" }  ,
                new District()  {Id=640 ,   CityId =55,Name ="Altınekin	",Code =  "332" }  ,
                new District()  {Id=641 ,   CityId =55,Name ="Beyşehir",Code =  "332" }  ,
                new District()  {Id=642 ,   CityId =55,Name ="Bozkır	",Code =  "332" }  ,
                new District()  {Id=643 ,   CityId =55,Name ="Çeltik	",Code =  "332" }  ,
                new District()  {Id=644 ,   CityId =55,Name ="Cihanbeyli	",Code =  "332" }  ,
                new District()  {Id=645 ,   CityId =55,Name ="Çumra	",Code =  "332" }  ,
                new District()  {Id=646 ,   CityId =55,Name ="Derbent	" ,   Code =  "332" }  ,
                new District()  {Id=647 ,   CityId =55,Name ="Derebucak	",Code =  "332" }  ,
                new District()  {Id=648 ,   CityId =55,Name ="Doğanhisar	",Code =  "332" }  ,
                new District()  {Id=649 ,   CityId =55,Name ="Emirgazi",Code =  "332" }  ,
                new District()  {Id=650 ,   CityId =55,Name ="Ereğli	",Code =  "332" }  ,
                new District()  {Id=651 ,   CityId =55,Name ="Güneysınır	",Code =  "332" }  ,
                new District()  {Id=652 ,   CityId =55,Name ="Hadim	",Code =  "332" }  ,
                new District()  {Id=653 ,   CityId =55,Name ="Halkapınar	",Code =  "332" }  ,
                new District()  {Id=654 ,   CityId =55,Name ="Hüyük	",Code =  "332" }  ,
                new District()  {Id=655 ,   CityId =55,Name ="Ilgın	",Code =  "332" }  ,
                new District()  {Id=656 ,   CityId =55,Name ="Kadınhanı	",Code =  "332" }  ,
                new District()  {Id=657 ,   CityId =55,Name ="Karapınar	",Code =  "332" }  ,
                new District()  {Id=658 ,   CityId =55,Name ="Karatay	" ,   Code =  "332" }  ,
                new District()  {Id=659 ,   CityId =55,Name ="Kulu",Code =  "332" }  ,
                new District()  {Id=660 ,   CityId =55,Name ="Meram	",Code =  "332" }  ,
                new District()  {Id=661 ,   CityId =55,Name ="Sarayönü",Code =  "332" }  ,
                new District()  {Id=662 ,   CityId =55,Name ="Selçuklu",Code =  "332" }  ,
                new District()  {Id=663 ,   CityId =55,Name ="Seydişehir	",Code =  "332" }  ,
                new District()  {Id=664 ,   CityId =55,Name ="Taşkent	" ,   Code =  "332" }  ,
                new District()  {Id=665 ,   CityId =55,Name ="Tuzlukçu",Code =  "332" }  ,
                new District()  {Id=666 ,   CityId =55,Name ="Yalıhüyük	",Code =  "332" }  ,
                new District()  {Id=667 ,   CityId =55,Name ="Yunak	",Code =  "332" }  ,
                new District()  {Id=668 ,   CityId =56,Name ="Altıntaş",Code =  "274" }  ,
                new District()  {Id=669 ,   CityId =56,Name ="Aslanapa",Code =  "274" }  ,
                new District()  {Id=670 ,   CityId =56,Name ="Çavdarhisar	" ,   Code =  "274" }  ,
                new District()  {Id=671 ,   CityId =56,Name ="Domaniç	" ,   Code =  "274" }  ,
                new District()  {Id=672 ,   CityId =56,Name ="Dumlupınar	",Code =  "274" }  ,
                new District()  {Id=673 ,   CityId =56,Name ="Emet",Code =  "274" }  ,
                new District()  {Id=674 ,   CityId =56,Name ="Gediz	",Code =  "274" }  ,
                new District()  {Id=675 ,   CityId =56,Name ="Hisarcık",Code =  "274" }  ,
                new District()  {Id=676 ,   CityId =56,Name ="Merkez	",Code =  "274" }  ,
                new District()  {Id=677 ,   CityId =56,Name ="Pazarlar",Code =  "274" }  ,
                new District()  {Id=678 ,   CityId =56,Name ="Şaphane	" ,   Code =  "274" }  ,
                new District()  {Id=679 ,   CityId =56,Name ="Simav	",Code =  "274" }  ,
                new District()  {Id=680 ,   CityId =56,Name ="Tavşanlı",Code =  "274" }  ,
                new District()  {Id=681 ,   CityId =57,Name ="Akçadağ	" ,   Code =  "422" }  ,
                new District()  {Id=682 ,   CityId =57,Name ="Arapgir	" ,   Code =  "422" }  ,
                new District()  {Id=683 ,   CityId =57,Name ="Arguvan	" ,   Code =  "422" }  ,
                new District()  {Id=684 ,   CityId =57,Name ="Battalgazi	",Code =  "422" }  ,
                new District()  {Id=685 ,   CityId =57,Name ="Darende	" ,   Code =  "422" }  ,
                new District()  {Id=686 ,   CityId =57,Name ="Doğanşehir	",Code =  "422" }  ,
                new District()  {Id=687 ,   CityId =57,Name ="Doğanyol",Code =  "422" }  ,
                new District()  {Id=688 ,   CityId =57,Name ="Hekimhan",Code =  "422" }  ,
                new District()  {Id=689 ,   CityId =57,Name ="Kale",Code =  "422" }  ,
                new District()  {Id=690 ,   CityId =57,Name ="Kuluncak",Code =  "422" }  ,
                new District()  {Id=691 ,   CityId =57,Name ="Pütürge	" ,   Code =  "422" }  ,
                new District()  {Id=692 ,   CityId =57,Name ="Yazıhan	" ,   Code =  "422" }  ,
                new District()  {Id=693 ,   CityId =57,Name ="Yeşilyurt	",Code =  "422" }  ,
                new District()  {Id=694 ,   CityId =58,Name ="Ahmetli	" ,   Code =  "236" }  ,
                new District()  {Id=695 ,   CityId =58,Name ="Akhisar	" ,   Code =  "236" }  ,
                new District()  {Id=696 ,   CityId =58,Name ="Alaşehir",Code =  "236" }  ,
                new District()  {Id=697 ,   CityId =58,Name ="Demirci	" ,   Code =  "236" }  ,
                new District()  {Id=698 ,   CityId =58,Name ="Gölmarmara	",Code =  "236" }  ,
                new District()  {Id=699 ,   CityId =58,Name ="Gördes	",Code =  "236" }  ,
                new District()  {Id=700 ,   CityId =58,Name ="Kırkağaç",Code =  "236" }  ,
                new District()  {Id=701 ,   CityId =58,Name ="Köprübaşı	",Code =  "236" }  ,
                new District()  {Id=702 ,   CityId =58,Name ="Kula",Code =  "236" }  ,
                new District()  {Id=703 ,   CityId =58,Name ="Salihli	" ,   Code =  "236" }  ,
                new District()  {Id=704 ,   CityId =58,Name ="Sarıgöl	" ,   Code =  "236" }  ,
                new District()  {Id=705 ,   CityId =58,Name ="Saruhanlı	",Code =  "236" }  ,
                new District()  {Id=706 ,   CityId =58,Name ="Şehzadeler	",Code =  "236" }  ,
                new District()  {Id=707 ,   CityId =58,Name ="Selendi	" ,   Code =  "236" }  ,
                new District()  {Id=708 ,   CityId =58,Name ="Soma",Code =  "236" }  ,
                new District()  {Id=709 ,   CityId =58,Name ="Turgutlu",Code =  "236" }  ,
                new District()  {Id=710 ,   CityId =58,Name ="Yunusemre	",Code =  "236" }  ,
                new District()  {Id=711 ,   CityId =59,Name ="Artuklu	" ,   Code =  "482" }  ,
                new District()  {Id=712 ,   CityId =59,Name ="Dargeçit",Code =  "482" }  ,
                new District()  {Id=713 ,   CityId =59,Name ="Derik	",Code =  "482" }  ,
                new District()  {Id=714 ,   CityId =59,Name ="Kızıltepe	",Code =  "482" }  ,
                new District()  {Id=715 ,   CityId =59,Name ="Mazıdağı",Code =  "482" }  ,
                new District()  {Id=716 ,   CityId =59,Name ="Midyat	",Code =  "482" }  ,
                new District()  {Id=717 ,   CityId =59,Name ="Nusaybin",Code =  "482" }  ,
                new District()  {Id=718 ,   CityId =59,Name ="Ömerli	",Code =  "482" }  ,
                new District()  {Id=719 ,   CityId =59,Name ="Savur	",Code =  "482" }  ,
                new District()  {Id=720 ,   CityId =59,Name ="Yeşilli	" ,   Code =  "482" }  ,
                new District()  {Id=721 ,   CityId =60,Name ="Bodrum	",Code =  "252" }  ,
                new District()  {Id=722 ,   CityId =60,Name ="Dalaman	" ,   Code =  "252" }  ,
                new District()  {Id=723 ,   CityId =60,Name ="Datça	",Code =  "252" }  ,
                new District()  {Id=724 ,   CityId =60,Name ="Fethiye	" ,   Code =  "252" }  ,
                new District()  {Id=725 ,   CityId =60,Name ="Kavaklıdere	" ,   Code =  "252" }  ,
                new District()  {Id=726 ,   CityId =60,Name ="Köyceğiz",Code =  "252" }  ,
                new District()  {Id=727 ,   CityId =60,Name ="Marmaris",Code =  "252" }  ,
                new District()  {Id=728 ,   CityId =60,Name ="Menteşe	" ,   Code =  "252" }  ,
                new District()  {Id=729 ,   CityId =60,Name ="Milas	",Code =  "252" }  ,
                new District()  {Id=730 ,   CityId =60,Name ="Ortaca	",Code =  "252" }  ,
                new District()  {Id=731 ,   CityId =60,Name ="Seydikemer	",Code =  "252" }  ,
                new District()  {Id=732 ,   CityId =60,Name ="Ula	" ,   Code =  "252" }  ,
                new District()  {Id=733 ,   CityId =60,Name ="Yatağan	" ,   Code =  "252" }  ,
                new District()  {Id=734 ,   CityId =61,Name ="Bulanık	" ,   Code =  "436" }  ,
                new District()  {Id=735 ,   CityId =61,Name ="Hasköy	",Code =  "436" }  ,
                new District()  {Id=736 ,   CityId =61,Name ="Korkut	",Code =  "436" }  ,
                new District()  {Id=737 ,   CityId =61,Name ="Malazgirt	",Code =  "436" }  ,
                new District()  {Id=738 ,   CityId =61,Name ="Merkez	",Code =  "436" }  ,
                new District()  {Id=739 ,   CityId =61,Name ="Varto	",Code =  "436" }  ,
                new District()  {Id=740 ,   CityId =62,Name ="Acıgöl	",Code =  "384" }  ,
                new District()  {Id=741 ,   CityId =62,Name ="Avanos	",Code =  "384" }  ,
                new District()  {Id=742 ,   CityId =62,Name ="Derinkuyu	",Code =  "384" }  ,
                new District()  {Id=743 ,   CityId =62,Name ="Gülşehir",Code =  "384" }  ,
                new District()  {Id=744 ,   CityId =62,Name ="Hacıbektaş	",Code =  "384" }  ,
                new District()  {Id=745 ,   CityId =62,Name ="Kozaklı	" ,   Code =  "384" }  ,
                new District()  {Id=746 ,   CityId =62,Name ="Merkez	",Code =  "384" }  ,
                new District()  {Id=747 ,   CityId =62,Name ="Ürgüp	",Code =  "384" }  ,
                new District()  {Id=748 ,   CityId =63,Name ="Altunhisar	",Code =  "388" }  ,
                new District()  {Id=749 ,   CityId =63,Name ="Bor	" ,   Code =  "388" }  ,
                new District()  {Id=750 ,   CityId =63,Name ="Çamardı	" ,   Code =  "388" }  ,
                new District()  {Id=751 ,   CityId =63,Name ="Çiftlik	" ,   Code =  "388" }  ,
                new District()  {Id=752 ,   CityId =63,Name ="Merkez	",Code =  "388" }  ,
                new District()  {Id=753 ,   CityId =63,Name ="Ulukışla",Code =  "388" }  ,
                new District()  {Id=754 ,   CityId =64,Name ="Akkuş	",Code =  "452" }  ,
                new District()  {Id=755 ,   CityId =64,Name ="Altınordu	",Code =  "452" }  ,
                new District()  {Id=756 ,   CityId =64,Name ="Aybastı	" ,   Code =  "452" }  ,
                new District()  {Id=757 ,   CityId =64,Name ="Çamaş	",Code =  "452" }  ,
                new District()  {Id=758 ,   CityId =64,Name ="Çatalpınar	",Code =  "452" }  ,
                new District()  {Id=759 ,   CityId =64,Name ="Çaybaşı	" ,   Code =  "452" }  ,
                new District()  {Id=760 ,   CityId =64,Name ="Fatsa	",Code =  "452" }  ,
                new District()  {Id=761 ,   CityId =64,Name ="Gölköy	",Code =  "452" }  ,
                new District()  {Id=762 ,   CityId =64,Name ="Gülyalı	" ,   Code =  "452" }  ,
                new District()  {Id=763 ,   CityId =64,Name ="Gürgentepe	",Code =  "452" }  ,
                new District()  {Id=764 ,   CityId =64,Name ="İkizce	",Code =  "452" }  ,
                new District()  {Id=765 ,   CityId =64,Name ="Kabadüz	" ,   Code =  "452" }  ,
                new District()  {Id=766 ,   CityId =64,Name ="Kabataş	" ,   Code =  "452" }  ,
                new District()  {Id=767 ,   CityId =64,Name ="Korgan	",Code =  "452" }  ,
                new District()  {Id=768 ,   CityId =64,Name ="Kumru	",Code =  "452" }  ,
                new District()  {Id=769 ,   CityId =64,Name ="Mesudiye",Code =  "452" }  ,
                new District()  {Id=770 ,   CityId =64,Name ="Perşembe",Code =  "452" }  ,
                new District()  {Id=771 ,   CityId =64,Name ="Ulubey	",Code =  "452" }  ,
                new District()  {Id=772 ,   CityId =64,Name ="Ünye",Code =  "452" }  ,
                new District()  {Id=773 ,   CityId =65,Name ="Bahçe	",Code =  "328" }  ,
                new District()  {Id=774 ,   CityId =65,Name ="Düziçi	",Code =  "328" }  ,
                new District()  {Id=775 ,   CityId =65,Name ="Hasanbeyli	",Code =  "328" }  ,
                new District()  {Id=776 ,   CityId =65,Name ="Kadirli	" ,   Code =  "328" }  ,
                new District()  {Id=777 ,   CityId =65,Name ="Merkez	",Code =  "328" }  ,
                new District()  {Id=778 ,   CityId =65,Name ="Sumbas	",Code =  "328" }  ,
                new District()  {Id=779 ,   CityId =65,Name ="Toprakkale	",Code =  "328" }  ,
                new District()  {Id=780 ,   CityId =66,Name ="Ardeşen	" ,   Code =  "464" }  ,
                new District()  {Id=781 ,   CityId =66,Name ="Çamlıhemşin	" ,   Code =  "464" }  ,
                new District()  {Id=782 ,   CityId =66,Name ="Çayeli	",Code =  "464" }  ,
                new District()  {Id=783 ,   CityId =66,Name ="Derepazarı	",Code =  "464" }  ,
                new District()  {Id=784 ,   CityId =66,Name ="Fındıklı",Code =  "464" }  ,
                new District()  {Id=785 ,   CityId =66,Name ="Güneysu	" ,   Code =  "464" }  ,
                new District()  {Id=786 ,   CityId =66,Name ="Hemşin	",Code =  "464" }  ,
                new District()  {Id=787 ,   CityId =66,Name ="İkizdere",Code =  "464" }  ,
                new District()  {Id=788 ,   CityId =66,Name ="İyidere	" ,   Code =  "464" }  ,
                new District()  {Id=789 ,   CityId =66,Name ="Kalkandere	",Code =  "464" }  ,
                new District()  {Id=790 ,   CityId =66,Name ="Merkez	",Code =  "464" }  ,
                new District()  {Id=791 ,   CityId =66,Name ="Pazar	",Code =  "464" }  ,
                new District()  {Id=792 ,   CityId =67,Name ="Adapazarı	",Code =  "264" }  ,
                new District()  {Id=793 ,   CityId =67,Name ="Akyazı	",Code =  "264" }  ,
                new District()  {Id=794 ,   CityId =67,Name ="Arifiye	" ,   Code =  "264" }  ,
                new District()  {Id=795 ,   CityId =67,Name ="Erenler	" ,   Code =  "264" }  ,
                new District()  {Id=796 ,   CityId =67,Name ="Ferizli	" ,   Code =  "264" }  ,
                new District()  {Id=797 ,   CityId =67,Name ="Geyve	",Code =  "264" }  ,
                new District()  {Id=798 ,   CityId =67,Name ="Hendek	",Code =  "264" }  ,
                new District()  {Id=799 ,   CityId =67,Name ="Karapürçek	",Code =  "264" }  ,
                new District()  {Id=800 ,   CityId =67,Name ="Karasu	",Code =  "264" }  ,
                new District()  {Id=801 ,   CityId =67,Name ="Kaynarca",Code =  "264" }  ,
                new District()  {Id=802 ,   CityId =67,Name ="Kocaali	" ,   Code =  "264" }  ,
                new District()  {Id=803 ,   CityId =67,Name ="Pamukova",Code =  "264" }  ,
                new District()  {Id=804 ,   CityId =67,Name ="Sapanca	" ,   Code =  "264" }  ,
                new District()  {Id=805 ,   CityId =67,Name ="Serdivan",Code =  "264" }  ,
                new District()  {Id=806 ,   CityId =67,Name ="Söğütlü	" ,   Code =  "264" }  ,
                new District()  {Id=807 ,   CityId =67,Name ="Taraklı	" ,   Code =  "362" }  ,
                new District()  {Id=808 ,   CityId =68,Name ="19 Mayıs",Code =  "362" }  ,
                new District()  {Id=809 ,   CityId =68,Name ="Alaçam	",Code =  "362" }  ,
                new District()  {Id=810 ,   CityId =68,Name ="Asarcık	" ,   Code =  "362" }  ,
                new District()  {Id=811 ,   CityId =68,Name ="Atakum	",Code =  "362" }  ,
                new District()  {Id=812 ,   CityId =68,Name ="Ayvacık	" ,   Code =  "362" }  ,
                new District()  {Id=813 ,   CityId =68,Name ="Bafra	",Code =  "362" }  ,
                new District()  {Id=814 ,   CityId =68,Name ="Canik	",Code =  "362" }  ,
                new District()  {Id=815 ,   CityId =68,Name ="Çarşamba",Code =  "362" }  ,
                new District()  {Id=816 ,   CityId =68,Name ="Havza	",Code =  "362" }  ,
                new District()  {Id=817 ,   CityId =68,Name ="İlkadım	" ,   Code =  "362" }  ,
                new District()  {Id=818 ,   CityId =68,Name ="Kavak	",Code =  "362" }  ,
                new District()  {Id=819 ,   CityId =68,Name ="Ladik	",Code =  "362" }  ,
                new District()  {Id=820 ,   CityId =68,Name ="Salıpazarı	",Code =  "362" }  ,
                new District()  {Id=821 ,   CityId =68,Name ="Tekkeköy",Code =  "362" }  ,
                new District()  {Id=822 ,   CityId =68,Name ="Terme	",Code =  "362" }  ,
                new District()  {Id=823 ,   CityId =68,Name ="Vezirköprü	",Code =  "362" }  ,
                new District()  {Id=824 ,   CityId =68,Name ="Yakakent",Code =  "362" }  ,
                new District()  {Id=825 ,   CityId =69,Name ="Baykan	",Code =  "484" }  ,
                new District()  {Id=826 ,   CityId =69,Name ="Eruh",Code =  "484" }  ,
                new District()  {Id=827 ,   CityId =69,Name ="Kurtalan",Code =  "484" }  ,
                new District()  {Id=828 ,   CityId =69,Name ="Merkez	",Code =  "484" }  ,
                new District()  {Id=829 ,   CityId =69,Name ="Pervari	" ,   Code =  "484" }  ,
                new District()  {Id=830 ,   CityId =69,Name ="Şirvan	",Code =  "484" }  ,
                new District()  {Id=831 ,   CityId =69,Name ="Tillo	",Code =  "484" }  ,
                new District()  {Id=832 ,   CityId =70,Name ="Ayancık	" ,   Code =  "368" }  ,
                new District()  {Id=833 ,   CityId =70,Name ="Boyabat	" ,   Code =  "368" }  ,
                new District()  {Id=834 ,   CityId =70,Name ="Dikmen	",Code =  "368" }  ,
                new District()  {Id=835 ,   CityId =70,Name ="Durağan	" ,   Code =  "368" }  ,
                new District()  {Id=836 ,   CityId =70,Name ="Erfelek	" ,   Code =  "368" }  ,
                new District()  {Id=837 ,   CityId =70,Name ="Gerze	",Code =  "368" }  ,
                new District()  {Id=838 ,   CityId =70,Name ="Merkez	",Code =  "368" }  ,
                new District()  {Id=839 ,   CityId =70,Name ="Saraydüzü	",Code =  "368" }  ,
                new District()  {Id=840 ,   CityId =70,Name ="Türkeli	" ,   Code =  "368" }  ,
                new District()  {Id=841 ,   CityId =71,Name ="Akıncılar	",Code =  "346" }  ,
                new District()  {Id=842 ,   CityId =71,Name ="Altınyayla	",Code =  "346" }  ,
                new District()  {Id=843 ,   CityId =71,Name ="Divriği	" ,   Code =  "346" }  ,
                new District()  {Id=844 ,   CityId =71,Name ="Doğanşar",Code =  "346" }  ,
                new District()  {Id=845 ,   CityId =71,Name ="Gemerek	" ,   Code =  "346" }  ,
                new District()  {Id=846 ,   CityId =71,Name ="Gölova	",Code =  "346" }  ,
                new District()  {Id=847 ,   CityId =71,Name ="Gürün	",Code =  "346" }  ,
                new District()  {Id=848 ,   CityId =71,Name ="Hafik	",Code =  "346" }  ,
                new District()  {Id=849 ,   CityId =71,Name ="İmranlı	" ,   Code =  "346" }  ,
                new District()  {Id=850 ,   CityId =71,Name ="Kangal	",Code =  "346" }  ,
                new District()  {Id=851 ,   CityId =71,Name ="Koyulhisar	",Code =  "346" }  ,
                new District()  {Id=852 ,   CityId =71,Name ="Merkez	",Code =  "346" }  ,
                new District()  {Id=853 ,   CityId =71,Name ="Şarkışla",Code =  "346" }  ,
                new District()  {Id=854 ,   CityId =71,Name ="Suşehri	" ,   Code =  "346" }  ,
                new District()  {Id=855 ,   CityId =71,Name ="Ulaş",Code =  "346" }  ,
                new District()  {Id=856 ,   CityId =71,Name ="Yıldızeli	",Code =  "346" }  ,
                new District()  {Id=857 ,   CityId =71,Name ="Zara",Code =  "346" }  ,
                new District()  {Id=858 ,   CityId =72,Name ="Akçakale",Code =  "414" }  ,
                new District()  {Id=859 ,   CityId =72,Name ="Birecik	" ,   Code =  "414" }  ,
                new District()  {Id=860 ,   CityId =72,Name ="Bozova	",Code =  "414" }  ,
                new District()  {Id=861 ,   CityId =72,Name ="Ceylanpınar	" ,   Code =  "414" }  ,
                new District()  {Id=862 ,   CityId =72,Name ="Eyyübiye",Code =  "414" }  ,
                new District()  {Id=863 ,   CityId =72,Name ="Halfeti	" ,   Code =  "414" }  ,
                new District()  {Id=864 ,   CityId =72,Name ="Haliliye",Code =  "414" }  ,
                new District()  {Id=865 ,   CityId =72,Name ="Harran	",Code =  "414" }  ,
                new District()  {Id=866 ,   CityId =72,Name ="Hilvan	",Code =  "414" }  ,
                new District()  {Id=867 ,   CityId =72,Name ="Karaköprü	",Code =  "414" }  ,
                new District()  {Id=868 ,   CityId =72,Name ="Siverek	" ,   Code =  "414" }  ,
                new District()  {Id=869 ,   CityId =72,Name ="Suruç	",Code =  "414" }  ,
                new District()  {Id=870 ,   CityId =72,Name ="Viranşehir	",Code =  "414" }  ,
                new District()  {Id=871 ,   CityId =73,Name ="Beytüşşebap	" ,   Code =  "486" }  ,
                new District()  {Id=872 ,   CityId =73,Name ="Cizre	",Code =  "486" }  ,
                new District()  {Id=873 ,   CityId =73,Name ="Güçlükonak	",Code =  "486" }  ,
                new District()  {Id=874 ,   CityId =73,Name ="İdil",Code =  "486" }  ,
                new District()  {Id=875 ,   CityId =73,Name ="Merkez	",Code =  "486" }  ,
                new District()  {Id=876 ,   CityId =73,Name ="Silopi	",Code =  "486" }  ,
                new District()  {Id=877 ,   CityId =73,Name ="Uludere	" ,   Code =  "486" }  ,
                new District()  {Id=878 ,   CityId =74,Name ="Çerkezköy	",Code =  "282" }  ,
                new District()  {Id=879 ,   CityId =74,Name ="Çorlu	",Code =  "282" }  ,
                new District()  {Id=880 ,   CityId =74,Name ="Ergene	",Code =  "282" }  ,
                new District()  {Id=881 ,   CityId =74,Name ="Hayrabolu	",Code =  "282" }  ,
                new District()  {Id=882 ,   CityId =74,Name ="Kapaklı	" ,   Code =  "282" }  ,
                new District()  {Id=883 ,   CityId =74,Name ="Malkara	" ,   Code =  "282" }  ,
                new District()  {Id=884 ,   CityId =74,Name ="Marmaraereğlisi	" ,   Code =  "282" }  ,
                new District()  {Id=885 ,   CityId =74,Name ="Muratlı	" ,   Code =  "282" }  ,
                new District()  {Id=886 ,   CityId =74,Name ="Saray	",Code =  "282" }  ,
                new District()  {Id=887 ,   CityId =74,Name ="Şarköy	",Code =  "282" }  ,
                new District()  {Id=888 ,   CityId =74,Name ="Süleymanpaşa",Code =  "282" }  ,
                new District()  {Id=889 ,   CityId =75,Name ="Almus	",Code =  "356" }  ,
                new District()  {Id=890 ,   CityId =75,Name ="Artova	",Code =  "356" }  ,
                new District()  {Id=891 ,   CityId =75,Name ="Başçiftlik	",Code =  "356" }  ,
                new District()  {Id=892 ,   CityId =75,Name ="Erbaa	",Code =  "356" }  ,
                new District()  {Id=893 ,   CityId =75,Name ="Merkez	",Code =  "356" }  ,
                new District()  {Id=894 ,   CityId =75,Name ="Niksar	",Code =  "356" }  ,
                new District()  {Id=895 ,   CityId =75,Name ="Pazar	",Code =  "356" }  ,
                new District()  {Id=896 ,   CityId =75,Name ="Reşadiye",Code =  "356" }  ,
                new District()  {Id=897 ,   CityId =75,Name ="Sulusaray	",Code =  "356" }  ,
                new District()  {Id=898 ,   CityId =75,Name ="Turhal	",Code =  "356" }  ,
                new District()  {Id=899 ,   CityId =75,Name ="Yeşilyurt	",Code =  "356" }  ,
                new District()  {Id=900 ,   CityId =75,Name ="Zile",Code =  "356" }  ,
                new District()  {Id=901 ,   CityId =76,Name ="Akçaabat",Code =  "462" }  ,
                new District()  {Id=902 ,   CityId =76,Name ="Araklı	",Code =  "462" }  ,
                new District()  {Id=903 ,   CityId =76,Name ="Arsin	",Code =  "462" }  ,
                new District()  {Id=904 ,   CityId =76,Name ="Beşikdüzü	",Code =  "462" }  ,
                new District()  {Id=905 ,   CityId =76,Name ="Çarşıbaşı	",Code =  "462" }  ,
                new District()  {Id=906 ,   CityId =76,Name ="Çaykara	" ,   Code =  "462" }  ,
                new District()  {Id=907 ,   CityId =76,Name ="Dernekpazarı",Code =  "462" }  ,
                new District()  {Id=908 ,   CityId =76,Name ="Düzköy	",Code =  "462" }  ,
                new District()  {Id=909 ,   CityId =76,Name ="Hayrat	",Code =  "462" }  ,
                new District()  {Id=910 ,   CityId =76,Name ="Köprübaşı	",Code =  "462" }  ,
                new District()  {Id=911 ,   CityId =76,Name ="Maçka	",Code =  "462" }  ,
                new District()  {Id=912 ,   CityId =76,Name ="Of	",Code =  "462" }  ,
                new District()  {Id=913 ,   CityId =76,Name ="Ortahisar	",Code =  "462" }  ,
                new District()  {Id=914 ,   CityId =76,Name ="Şalpazarı	",Code =  "462" }  ,
                new District()  {Id=915 ,   CityId =76,Name ="Sürmene	" ,   Code =  "462" }  ,
                new District()  {Id=916 ,   CityId =76,Name ="Tonya	",Code =  "462" }  ,
                new District()  {Id=917 ,   CityId =76,Name ="Vakfıkebir	",Code =  "462" }  ,
                new District()  {Id=918 ,   CityId =76,Name ="Yomra	",Code =  "462" }  ,
                new District()  {Id=919 ,   CityId =77,Name ="Çemişgezek	",Code =  "428" }  ,
                new District()  {Id=920 ,   CityId =77,Name ="Hozat	",Code =  "428" }  ,
                new District()  {Id=921 ,   CityId =77,Name ="Mazgirt	" ,   Code =  "428" }  ,
                new District()  {Id=922 ,   CityId =77,Name ="Merkez	",Code =  "428" }  ,
                new District()  {Id=923 ,   CityId =77,Name ="Nazımiye",Code =  "428" }  ,
                new District()  {Id=924 ,   CityId =77,Name ="Ovacık	",Code =  "428" }  ,
                new District()  {Id=925 ,   CityId =77,Name ="Pertek	",Code =  "428" }  ,
                new District()  {Id=926 ,   CityId =77,Name ="Pülümür	" ,   Code =  "428" }  ,
                new District()  {Id=927 ,   CityId =78,Name ="Banaz	",Code =  "276" }  ,
                new District()  {Id=928 ,   CityId =78,Name ="Eşme",Code =  "276" }  ,
                new District()  {Id=929 ,   CityId =78,Name ="Karahallı	",Code =  "276" }  ,
                new District()  {Id=930 ,   CityId =78,Name ="Merkez	",Code =  "276" }  ,
                new District()  {Id=931 ,   CityId =78,Name ="Sivaslı	" ,   Code =  "276" }  ,
                new District()  {Id=932 ,   CityId =78,Name ="Ulubey	",Code =  "276" }  ,
                new District()  {Id=933 ,   CityId =79,Name ="Bahçesaray	",Code =  "432" }  ,
                new District()  {Id=934 ,   CityId =79,Name ="Başkale	" ,   Code =  "432" }  ,
                new District()  {Id=935 ,   CityId =79,Name ="Çaldıran",Code =  "432" }  ,
                new District()  {Id=936 ,   CityId =79,Name ="Çatak	",Code =  "432" }  ,
                new District()  {Id=937 ,   CityId =79,Name ="Edremit	" ,   Code =  "432" }  ,
                new District()  {Id=938 ,   CityId =79,Name ="Erciş	",Code =  "432" }  ,
                new District()  {Id=939 ,   CityId =79,Name ="Gevaş	",Code =  "432" }  ,
                new District()  {Id=940 ,   CityId =79,Name ="Gürpınar",Code =  "432" }  ,
                new District()  {Id=941 ,   CityId =79,Name ="İpekyolu",Code =  "432" }  ,
                new District()  {Id=942 ,   CityId =79,Name ="Muradiye",Code =  "432" }  ,
                new District()  {Id=943 ,   CityId =79,Name ="Özalp	",Code =  "432" }  ,
                new District()  {Id=944 ,   CityId =79,Name ="Saray	",Code =  "432" }  ,
                new District()  {Id=945 ,   CityId =79,Name ="Tuşba	",Code =  "432" }  ,
                new District()  {Id=946 ,   CityId =80,Name ="Altınova",Code =  "226" }  ,
                new District()  {Id=947 ,   CityId =80,Name ="Armutlu	" ,   Code =  "226" }  ,
                new District()  {Id=948 ,   CityId =80,Name ="Çiftlikköy	",Code =  "226" }  ,
                new District()  {Id=949 ,   CityId =80,Name ="Çınarcık",Code =  "226" }  ,
                new District()  {Id=950 ,   CityId =80,Name ="Merkez	",Code =  "226" }  ,
                new District()  {Id=951 ,   CityId =80,Name ="Termal	",Code =  "226" }  ,
                new District()  {Id=952 ,   CityId =81,Name ="Akdağmadeni	" ,   Code =  "354" }  ,
                new District()  {Id=953 ,   CityId =81,Name ="Aydıncık",Code =  "354" }  ,
                new District()  {Id=954 ,   CityId =81,Name ="Boğazlıyan	",Code =  "354" }  ,
                new District()  {Id=955 ,   CityId =81,Name ="Çandır	",Code =  "354" }  ,
                new District()  {Id=956 ,   CityId =81,Name ="Çayıralan	",Code =  "354" }  ,
                new District()  {Id=957 ,   CityId =81,Name ="Çekerek	" ,   Code =  "354" }  ,
                new District()  {Id=958 ,   CityId =81,Name ="Kadışehri	",Code =  "354" }  ,
                new District()  {Id=959 ,   CityId =81,Name ="Merkez	",Code =  "354" }  ,
                new District()  {Id=960 ,   CityId =81,Name ="Saraykent	",Code =  "354" }  ,
                new District()  {Id=961 ,   CityId =81,Name ="Sarıkaya",Code =  "354" }  ,
                new District()  {Id=962 ,   CityId =81,Name ="Şefaatli",Code =  "354" }  ,
                new District()  {Id=963 ,   CityId =81,Name ="Sorgun	",Code =  "354" }  ,
                new District()  {Id=964 ,   CityId =81,Name ="Yenifakılı	",Code =  "354" }  ,
                new District()  {Id=965 ,   CityId =81,Name ="Yerköy	",Code =  "354" }  ,
                new District()  {Id=966 ,   CityId =82,Name ="Alaplı	",Code =  "372" }  ,
                new District()  {Id=967 ,   CityId =82,Name ="Çaycuma	" ,   Code =  "372" }  ,
                new District()  {Id=968 ,   CityId =82,Name ="Devrek	",Code =  "372" }  ,
                new District()  {Id=969 ,   CityId =82,Name ="Ereğli	",Code =  "372" }  ,
                new District()  {Id=970 ,   CityId =82,Name ="Gökçebey",Code =  "372" }  ,
                new District()  {Id=971 ,   CityId =82,Name ="Kilimli	" ,   Code =  "372" }  ,
                new District()  {Id=972 ,   CityId =82,Name ="Kozlu	",Code =  "372" }  ,
                new District()  {Id=973 ,   CityId =82,Name ="Merkez	",Code =  "372" }
            };

            context.Districts.AddRange(districts);


            IList<Company> companies = new List<Company>()
            {
                new Company()
                {
                   Address = "Hebele Mahallesi,Hübele sokak,No hebel , Daire hübele Adana/Merkez",
                   DistrictId =1,
                   CompanyName = "OOPSHR Merkez",
                   MersisNumber = "MRS0133",
                   Phone = "+90 0900 555 55 55",
                   SSNumber = "1234d2311",
                   WebSite = "Hebele.com.tr"
                }
            };

            IEnumerable<Company> Inserted = context.Companies.AddRange(companies);

            IList<CompanyBranch> companyBranches = new List<CompanyBranch>()
            {
                new CompanyBranch()
                {
                    Adress = "Hebele Mahallesi,Hübele sokak,No hebel , Daire hübele Adana/Merkez",
                    BranchName = "OOPHR Adana",
                    DistrictId = 1,
                    MersisNumber = "MRS0133",
                    Phone = "+90 0900 555 55 55",
                    SSNumber = "1234d2311",
                    WebSite = "Hebele.com.tr",
                    CompanyId =Inserted.FirstOrDefault(z=>z.CompanyName == "OOPSHR Merkez").Id
             }
            };
            context.CompanyBranches.AddRange(companyBranches);


            IList<CompanyTitle> companyTitles = new List<CompanyTitle>() {
                    new CompanyTitle()
                    {
                        Name = "IK Müdürü",
                        Description = "Insan Kaynakları Müdürümüz",
                        CompanyId =Inserted.FirstOrDefault(z=>z.CompanyName == "OOPSHR Merkez").Id
                    }
            };
            context.CompanyTitles.AddRange(companyTitles);


            base.Seed(context);
        }
    }
}
